/**
 * Models of the architecture page: infrastructure asset management. See ../model.js for the format.
 * @module architecture/models/infra
 */
export const INFRA = [
  {
    id: "infra-assets", group: "infra", title: "Assets, their condition and what is known of it",
    summary: "Railway assets with a hidden true health that wears, faults drawn from it, and the condition known from inspections, live data and age.",
    description: "Each asset has a true health h (1 new … 0 worn out) that only the engine knows. It wears by a law that ends a life at h = 0.3, and fails with a rate that grows with wear. What the players see is the known condition: the last observation aged by the wear law (its uncertainty growing with time), or an estimate from the asset's age, mixed with live data where the asset reports itself. Grades 1 (as new) … 5 (deficient), 6 while a known fault is open.",
    files: ["web/arail/infra/catalog.js", "web/arail/infra/assets.js", "web/arail/infra/network.js"],
    classes: [
      {
        name: "Asset", file: "web/arail/infra/assets.js", kind: "class", role: "One asset: health, faults, observations.",
        attributes: ["t: object — its type from the catalogue", "h: number — true health (hidden)", "fault: object | null — an open fault", "obs: object | null — the last observation {h, sigma, t, source}", "data: number — completeness of its record", "retrofit: number — share of monitoring added"],
        operations: ["wear(rate, rng, opts) — one day of wear", "failureRate(h, loadFactor)", "repair(gain, t, startYear)", "renew(t, startYear, opts)", "observe(t, sigma, source, rng, opts)", "known(t, ctx) — {h, sigma, grade, source, live, fault}", "liveShare(assets)", "reportPath(assets) — who notices a fault"],
      },
      {
        name: "catalog", file: "web/arail/infra/catalog.js", kind: "module", role: "Grades, disciplines, asset types, interlocking generations, inspection methods, measures.",
        attributes: ["GRADES — 1 as new … 5 deficient, 6 restricting", "ASSET_TYPES — 13 types with IFC 4.3 class, life, costs, faults, inspection", "GENERATIONS — mechanical, relay, electronic, digital", "METHODS — walk, diagnose, drone, measurement train", "MEASURES — repair, renew, modernize, retrofit, upgrade"],
        operations: ["gradeOf(h)", "healthOf(g)", "hazardFactor(h)", "repairCap(ageY, lifeY)"],
      },
      {
        name: "assets", file: "web/arail/infra/assets.js", kind: "module", role: "The wear law, IFC GlobalIds, the generated network.",
        operations: ["wearRate(lifeY)", "healthAtAge(ageY, lifeY)", "healthAfter(h, years, rate)", "ifcGuid(id)", "generateAssets(model, net, opts)"],
      },
      {
        name: "Network", file: "web/arail/infra/network.js", kind: "class", role: "Lines with their km, the layout's place in them, the georeference (UTM → WGS 84).",
        attributes: ["lines: Map", "stations: Map", "georef: object — EPSG, easting, northing, rotation"],
        operations: ["at(lineId, km)", "fromLayout(pt)", "kmOfLayout(pt)", "driveMinutes(a, b, walkMin)", "toLonLat(p)"],
      },
    ],
    relations: [
      { from: "Asset", to: "catalog", kind: "depends" },
      { from: "assets", to: "Network", kind: "uses" },
    ],
    activities: [{
      id: "known", name: "What is known of an asset (Asset.known)",
      nodes: [
        ["s", "start"],
        ["a1", "action", "How much of it reports itself (live)", "Asset.liveShare"],
        ["d1", "decision", "Observed before?"],
        ["a2", "action", "The observation aged by the wear law; its uncertainty grows", "healthAfter"],
        ["a3", "action", "An estimate from its age", "healthAtAge"],
        ["m1", "merge"],
        ["d2", "decision", "Live data?"],
        ["a4", "action", "Mixed with the live reading", "Asset.known"],
        ["m2", "merge"],
        ["d3", "decision", "A known open fault?"],
        ["a5", "action", "Grade 6", "Asset.known"],
        ["a6", "action", "Grade from the known health", "gradeOf"],
        ["m3", "merge"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "a3", "no"], ["a2", "m1"], ["a3", "m1"], ["m1", "d2"], ["d2", "a4", "yes"], ["d2", "m2", "no"], ["a4", "m2"], ["m2", "d3"], ["d3", "a5", "yes"], ["d3", "a6", "no"], ["a5", "m3"], ["a6", "m3"], ["m3", "e"]],
    }],
    parameters: [
      { key: "georef", default: "EPSG 25833, 409700 / 5651200", meaning: "Where the invented district lies (UTM)." },
      { key: "placement", default: "station bahnhof, line 6250, km 21.1", meaning: "The layout's place in the network." },
      { key: "lines, stations, crossings", default: "the example district", meaning: "The network around the layout." },
      { key: "generate", default: "block 3 km, sections 3 km, masts 5 km …", meaning: "Assets generated along the lines." },
    ],
    rules: [
      "Grade value = 1 + 4.99 (1 − h); grade = ⌊value⌋, 1 … 5; 6 while a known fault is open.",
      "Wear: du/dt = r (1 + u), u = 1 − h, r = ln 1.7 / life (h = 0.3 at the end of its life); daily with noise, faster when servicing is overdue and with more trains.",
      "Faults per year = rate × size × (0.25 + 4 (1 − h)^2.5) × load.",
      "Known: σ = hypot(σ of the observation, 0.07 per year since); from the age only: 0.18; live share w mixes h and σ.",
      "Report path: monitored assets report themselves; field elements through their interlocking; otherwise the type's (driver, panel, diagnosis, passengers).",
    ],
  },
  {
    id: "infra-engine", group: "infra", title: "The asset management game over years",
    summary: "A discrete-event simulation over years: wear, faults and their report paths, staff in shifts, dispatch, inspections, decisions of the roles, money, the EBA audit and the score; every action is recorded.",
    description: "InfraEngine pops events from a queue in minutes since 1 January of the start year. Each day assets wear and may fail; a fault becomes known along its report path, a responder is dispatched (emergency team, day technician, on call, contractor), trains are held or delayed until it is fixed. Inspections follow the plans of the ALV; findings go to the ALV, proposals to the asset manager. Every player action goes through act() and is recorded: the engine is deterministic for a seed, so a game is saved as its actions and restored by running them again.",
    files: ["web/arail/infra/engine.js", "web/arail/infra/staff.js", "web/arail/infra/config.js"],
    classes: [
      {
        name: "InfraEngine", file: "web/arail/infra/engine.js", kind: "class", role: "The simulation over years.",
        attributes: ["queue: EventQueue", "now: number — minutes since 1 January of the start year", "assets: Map — Asset by id", "people: StaffMember[]", "backlog: object[] — tasks", "inbox: object[] — decisions waiting", "actions: object[] — what the players did", "balance: object — maintenance, replacement, own money", "years: object[] — the results"],
        operations: ["runTo(t, opts)", "act(name, ...args) — a player's action, recorded", "replay(actions)", "save()", "ask(q) — a decision for a role", "propose(measure, assets, opts)", "_fail(a, opts)", "_dispatch(f)", "_fixed(f)", "_inspected(a, method, r, opts)", "_closeYear(y)", "score(res)"],
      },
      {
        name: "ACTIONS", file: "web/arail/infra/engine.js", kind: "module", role: "What players can do (exported as INFRA_ACTIONS).",
        operations: ["decide(id, choice)", "propose(measure, assets, opts)", "plan(type, method, perYear)", "staff(discipline, role, count)", "oncall(on)", "inspect(assetId, method)", "fail(assetId)", "role(role, who)"],
      },
      { name: "StaffMember", file: "web/arail/infra/staff.js", kind: "class", extends: "Person", role: "ALV, day technician, emergency team or drone pilot.", attributes: ["busyUntil: number", "task: object — what the person is doing"], operations: ["employed(t)"] },
      { name: "staff", file: "web/arail/infra/staff.js", kind: "module", role: "Shifts and on call.", attributes: ["SHIFTS — early, late, night"], operations: ["makePeople(model, seed)", "shiftOf(p, t, model, people)", "onCallPerson(discipline, t, model, people)"] },
      { name: "config", file: "web/arail/infra/config.js", kind: "module", role: "Settings, scenarios, validation.", attributes: ["ROLES — the roles of the game", "INFRA_DEFAULTS", "PRESET_SCENARIOS"], operations: ["normalizeInfra(config, layout)", "applyScenario(config, scenario)", "validateInfra(cfg, layout)"] },
    ],
    relations: [
      { from: "InfraEngine", to: "EventQueue", kind: "composes", label: "queue" },
      { from: "InfraEngine", to: "Asset", kind: "composes", label: "assets *" },
      { from: "InfraEngine", to: "Network", kind: "composes", label: "net" },
      { from: "InfraEngine", to: "StaffMember", kind: "composes", label: "people *" },
      { from: "InfraEngine", to: "ProjectDesk", kind: "composes", label: "desk" },
      { from: "InfraEngine", to: "Plant", kind: "composes", label: "factory" },
      { from: "InfraEngine", to: "ACTIONS", kind: "depends", label: "act" },
      { from: "InfraEngine", to: "config", kind: "depends" },
    ],
    activities: [
      {
        id: "fault", name: "A fault from occurrence to repair",
        nodes: [
          ["s", "start"],
          ["m0", "merge"],
          ["a1", "action", "A day of wear", "Asset.wear", "asset"],
          ["d1", "decision", "A fault drawn?"],
          ["a2", "action", "Open the fault; its report path", "InfraEngine._fail", "asset"],
          ["a3", "action", "It becomes known (driver, panel, diagnosis, monitoring …)", "InfraEngine._known", "dispatcher"],
          ["x1", "send", "infra.fault"],
          ["a4", "action", "On the layout: trains at the station held", "InfrastructureSimulation._startDisruption", "world"],
          ["a5", "action", "Rank the responders", "InfraEngine._responders", "dispatcher"],
          ["d2", "decision", "Who goes?"],
          ["a6", "action", "Emergency team or on call", "InfraEngine._dispatch", "staff"],
          ["a7", "action", "A day technician leaves the day's plan", "InfraEngine._dropPlan", "staff"],
          ["a8", "action", "A contractor, after 150 min", "InfraEngine._dispatch", "staff"],
          ["m1", "merge"],
          ["a9", "action", "Drive there, repair (lognormal time)", "InfraEngine._dispatch", "staff"],
          ["a10", "action", "Delays and outages counted", "InfraEngine._accrue"],
          ["a11", "action", "Repaired, observed, paid; the trains run again", "InfraEngine._fixed"],
          ["x2", "send", "infra.fixed"],
          ["e", "end"],
        ],
        edges: [["s", "m0"], ["m0", "a1"], ["a1", "d1"], ["d1", "m0", "no: next day"], ["d1", "a2", "yes"], ["a2", "a3"], ["a3", "x1"], ["x1", "a4"], ["a4", "a5"], ["a5", "d2"], ["d2", "a6", "emergency, on call"], ["d2", "a7", "day technician"], ["d2", "a8", "nobody"], ["a6", "m1"], ["a7", "m1"], ["a8", "m1"], ["m1", "a9"], ["a9", "a10"], ["a10", "a11"], ["a11", "x2"], ["x2", "e"]],
      },
      {
        id: "inspection", name: "An inspection",
        nodes: [
          ["s", "start"],
          ["a1", "action", "The ALV plans inspections per type", "ACTIONS.plan", "ALV"],
          ["m1", "merge"],
          ["d1", "decision", "Due today, and how?"],
          ["a2", "action", "A task in the backlog", "InfraEngine._queueInspection"],
          ["a3", "action", "The workday is planned at 06:55", "InfraEngine._planDay"],
          ["d2", "decision", "Assigned today?"],
          ["a4", "action", "The technician inspects", "InfraEngine._taskDone", "technician"],
          ["a5", "action", "The measurement train runs", "InfraEngine._measurementRun"],
          ["m2", "merge"],
          ["a6", "action", "Observed: known condition, the rules' clock, the next date", "InfraEngine._inspected"],
          ["d3", "decision", "Grade 4 or worse, and worse than before?"],
          ["a7", "action", "A finding for the ALV", "InfraEngine.ask", "ALV"],
          ["d4", "decision", "The ALV's choice?"],
          ["a8", "action", "A proposal to the asset manager", "InfraEngine.propose", "asset manager"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "m1"], ["m1", "d1"], ["d1", "m1", "not due"], ["d1", "a2", "walk, diagnosis, drone"], ["d1", "a5", "measurement train"], ["a2", "a3"], ["a3", "d2"], ["d2", "a3", "no: next workday"], ["d2", "a4", "yes"], ["a4", "m2"], ["a5", "m2"], ["m2", "a6"], ["a6", "d3"], ["d3", "e", "no"], ["d3", "a7", "yes"], ["a7", "d4"], ["d4", "e", "watch"], ["d4", "a8", "repair, retrofit, renew"], ["a8", "e"]],
      },
      {
        id: "year", name: "The year's end",
        nodes: [
          ["s", "start"],
          ["a1", "action", "Open the year: budgets, plans", "InfraEngine._openYear"],
          ["a2", "action", "The EBA audit: inspections done in time?", "InfraEngine._audit", "EBA"],
          ["d1", "decision", "Compliance ≥ 95 %?"],
          ["a3", "action", "A fine", "InfraEngine.pay"],
          ["m1", "merge"],
          ["a4", "action", "Close the year: faults, money, the performance regime", "InfraEngine._closeYear"],
          ["d2", "decision", "Network grade worse than the target?"],
          ["a5", "action", "The Bund withholds a penalty", "InfraEngine._closeYear", "Bund"],
          ["m2", "merge"],
          ["a6", "action", "Result and score", "InfraEngine.score"],
          ["x1", "send", "infra.year"],
          ["d3", "decision", "Last year of the game?"],
          ["a7", "action", "New balances for the next year", "InfraEngine._startYear"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "a2"], ["a2", "d1"], ["d1", "m1", "yes"], ["d1", "a3", "no"], ["a3", "m1"], ["m1", "a4"], ["a4", "d2"], ["d2", "a5", "yes"], ["d2", "m2", "no"], ["a5", "m2"], ["m2", "a6"], ["a6", "x1"], ["x1", "d3"], ["d3", "e", "yes"], ["d3", "a7", "no"], ["a7", "a1"]],
      },
    ],
    parameters: [
      { key: "start_year, years", default: "2027, 5", meaning: "The game's years." },
      { key: "budgets", default: "maintenance 4.4 M€, replacement 9 M€, own 3 M€ a year", meaning: "Money of the infrastructure manager." },
      { key: "funding.target_grade", default: "3.2", meaning: "Network grade the Bund expects (else a penalty)." },
      { key: "staff", default: "day: track 6, signal 6, electric 3, station 2; emergency 5; 2 drone pilots", meaning: "People in shifts and on call." },
      { key: "costs", default: "72 000 € a person-year, contractor 115 €/h, call-out 150 min, 1 € per minute of delay", meaning: "What things cost." },
      { key: "roles", default: "dispatcher: computer; others: students", meaning: "Who decides: dispatcher, ALV, asset manager, planner …" },
      { key: "score", default: "condition 30, reliability 25, money 15, rules 15, information 15", meaning: "Weights of the score." },
    ],
    events: {
      emits: [
        { name: "infra.fault", payload: "fault, asset", when: "a fault becomes known" },
        { name: "infra.dispatch", payload: "fault, asset, person", when: "somebody is sent" },
        { name: "infra.fixed", payload: "fault, asset", when: "a fault is repaired" },
        { name: "infra.inspected", payload: "asset, method, known", when: "an inspection is done" },
        { name: "infra.decision", payload: "item", when: "a decision waits for a role" },
        { name: "infra.year", payload: "result", when: "a year ends" },
      ],
    },
    rules: [
      "Fault per day P = min(0.5, rate / 365); three times as likely during a defect period after a poor renewal.",
      "Known after: panel 3–6 min, diagnosis 1–2 min, monitoring 2–4 min, passengers next service + Exp(60 min), driver next service + U(0, headway) + 5 min.",
      "Responders: emergency team at once; a day technician (+10 min if busy); on call (+30 min, drive +15); contractor (+150 min).",
      "A fault holding trains: 30 min per train (cancelled); else its delay minutes; 1 € per minute.",
      "Audit fine = (0.95 − compliance) × 400 000 €, compliance = share inspected within 1.1 × the interval.",
      "Score: weighted mean of condition, reliability, money, rules and information, each 0 … 100.",
    ],
  },
  {
    id: "infra-projects", group: "infra", title: "Projects through the HOAI phases",
    summary: "Renewals and upgrades through the HOAI phases (LPH 1–9) with funding, the crossing agreement, planning approval, tenders and bids, possessions, acceptance and commissioning; a plant builds level crossing systems.",
    files: ["web/arail/infra/projects.js", "web/arail/infra/factory.js"],
    classes: [
      {
        name: "ProjectDesk", file: "web/arail/infra/projects.js", kind: "class", role: "The projects; their gates are decisions of the roles.",
        attributes: ["projects: Map — P-nn"],
        operations: ["create(opts) — LPH 1", "_enter(p, stage)", "stageDone(id, stage)", "decide(item, choice)", "_bids(p)", "_pay(p, what, share, opts)", "_complete(p) — in service, LPH 9"],
      },
      { name: "projects", file: "web/arail/infra/projects.js", kind: "module", role: "Stages, procedures, quality.", attributes: ["STAGES — LPH 1 … 9 and their gates", "PROCEDURES — direct, framework, open, negotiated"], operations: ["annuityFactor(rate, years)"] },
      { name: "Plant", file: "web/arail/infra/factory.js", kind: "class", role: "The level crossing plant: engineering, production, test, delivery.", operations: ["order(t, opts)", "advance(o, t, rng)", "leadWeeks()"] },
    ],
    relations: [
      { from: "ProjectDesk", to: "InfraEngine", kind: "uses", label: "e" },
      { from: "ProjectDesk", to: "Plant", kind: "uses", label: "level crossings" },
      { from: "ProjectDesk", to: "Asset", kind: "uses", label: "renew" },
    ],
    activities: [{
      id: "project", name: "A project through the HOAI phases",
      nodes: [
        ["s", "start"],
        ["a1", "action", "A proposal approved: the project, LPH 1", "ProjectDesk.create", "asset manager"],
        ["a2", "action", "The cost estimate", "ProjectDesk.stageDone", "planner"],
        ["d1", "decision", "An upgrade (funded by the Bund)?"],
        ["d2", "decision", "Funding granted (benefit-cost ratio)?"],
        ["m1", "merge"],
        ["a3", "action", "Crossing agreement; LPH 3–4", "ProjectDesk.stageDone", "planner"],
        ["d3", "decision", "Planning approval or plan check passed?", "ProjectDesk._enter", "authority"],
        ["m2", "merge"],
        ["a4", "action", "LPH 5–7: tender", "ProjectDesk._enter", "planner"],
        ["d4", "decision", "Any bid?", "ProjectDesk._bids"],
        ["a5", "action", "Award; possession booked; plant ordered", "ProjectDesk.decide", "asset manager"],
        ["a6", "action", "Construction, paid 30 % at the start, the rest at the end", "ProjectDesk._pay", "supervision"],
        ["d5", "decision", "Accepted and commissioned?"],
        ["a7", "action", "Defects fixed, documents handed in", "ProjectDesk.decide", "supervision"],
        ["a8", "action", "In service (LPH 9); the assets renewed", "ProjectDesk._complete"],
        ["x1", "send", "infra.asset.renewed"],
        ["e", "end"],
        ["f", "flowfinal"],
      ],
      edges: [["s", "a1"], ["a1", "a2"], ["a2", "d1"], ["d1", "d2", "yes"], ["d1", "m1", "no"], ["d2", "m1", "approved"], ["d2", "f", "rejected"], ["m1", "a3"], ["a3", "d3"], ["d3", "m2", "yes"], ["d3", "f", "refused"], ["m2", "a4"], ["a4", "d4"], ["d4", "m2", "none: tender again"], ["d4", "a5", "bids"], ["a5", "a6"], ["a6", "d5"], ["d5", "a7", "no"], ["a7", "d5"], ["d5", "a8", "yes"], ["a8", "x1"], ["x1", "e"]],
    }],
    parameters: [
      { key: "hoai", default: "shares 2, 20, 25, 8, 15, 10, 4, 15, 1 %; fee 14 %", meaning: "The phases and the planners' fees." },
      { key: "procurement", default: "EU threshold 5.404 M€, direct ≤ 150 000 €", meaning: "Which procedure a tender takes." },
      { key: "funding", default: "Bund 100 %, planning lump sum 18 %, 1.7 % over 30 years, ratio ≥ 1", meaning: "Funding of upgrades." },
      { key: "factory", default: "2 lines, 6 + 8 + 2 + 1 weeks, 15 % fail the test", meaning: "The level crossing plant." },
    ],
    events: { emits: [{ name: "infra.asset.renewed", payload: "asset, project", when: "a project puts the renewed asset into service" }] },
    rules: [
      "True cost = base × exp(bias + (σ + (1 − data) × 0.08) N); lean, normal or thorough planning changes bias, σ and the fee.",
      "Benefit-cost ratio = benefit a year × annuity factor (1.7 %, 30 years) / (estimate × 1.14).",
      "Bids = true cost × the firm's price × (1 + 0.15 × its load) × noise; the best of 0.7 × price + 0.3 × quality wins.",
      "Crossing agreement 60–120 days; planning approval 6 months; a planned possession at least 270 days after booking.",
    ],
  },
  {
    id: "infra-world", group: "infra", title: "Infrastructure on the layout",
    summary: "The engine on the world's clock with the layout's assets: their state drawn, vans over the streets, drones, faults holding the trains at the platforms; records and GeoJSON; the Infrastructure tab for the roles.",
    files: ["web/arail/infra/simulation.js", "web/arail/infra/objects.js", "web/arail/infra/disruptions.js", "web/arail/infra/export.js", "web/arail/infra/index.js", "web/app/infra.js"],
    classes: [
      {
        name: "InfrastructureSimulation", file: "web/arail/infra/simulation.js", kind: "class", extends: "Simulation", role: "The engine on the world's clock.",
        attributes: ["engine: InfraEngine | null", "offset: number — engine time = offset + the clock's minutes"],
        operations: ["step(dt)", "runTo(t, opts)", "runYear(opts)", "newGame(opts)", "save()", "load(saved)", "layoutAssets(net)", "failAsset(nameOrId)", "_event(name, payload) — engine events to the world (infra.*)", "_startDisruption(f, a)", "_syncFaults()", "draw(view)", "pickables(view) — the staff out with vans and drones", "card(hit)", "describeObject(o, card) — the condition of an asset, as known"],
      },
      { name: "AssetObject", file: "web/arail/infra/objects.js", kind: "class", extends: "LayoutObject", stereotype: "base class", role: "Signals, switches, balises, level crossings, masts, lifts, displays: their state drawn.", operations: ["state()", "draw(view)"] },
      { name: "MaintenanceBase", file: "web/arail/infra/objects.js", kind: "class", extends: "BuildingBase", role: "Where vans and drones start.", operations: ["slots()"] },
      { name: "export", file: "web/arail/infra/export.js", kind: "module", role: "Asset records and GIS.", operations: ["assetRecord(e, a)", "toGeoJSON(e)"] },
      { name: "InfraPanel", file: "web/app/infra.js", kind: "class", role: "The Infrastructure tab: roles, running fast, decisions, projects, saving games.", operations: ["can(what, item) — may the role do it?", "_act(name, args, text)", "update()"] },
    ],
    relations: [
      { from: "InfrastructureSimulation", to: "InfraEngine", kind: "composes", label: "engine" },
      { from: "InfrastructureSimulation", to: "DisruptionManager", kind: "uses", label: "infra-fault" },
      { from: "AssetObject", to: "InfrastructureSimulation", kind: "uses", label: "assetView" },
      { from: "InfraPanel", to: "InfrastructureSimulation", kind: "uses" },
      { from: "export", to: "InfraEngine", kind: "uses" },
    ],
    activities: [{
      id: "act", name: "A player's action, recorded and replayed",
      nodes: [
        ["s", "start"],
        ["d1", "decision", "May this role do it?", "InfraPanel.can", "player"],
        ["a1", "action", "Run the action", "InfraEngine.act"],
        ["d2", "decision", "Done?"],
        ["a2", "action", "Record it with its time", "InfraEngine.act"],
        ["a3", "action", "Save the game in the browser", "InfraPanel._autosave"],
        ["a4", "action", "Later (reload, edited layout): a new engine, quiet", "InfrastructureSimulation._build"],
        ["m1", "merge"],
        ["a5", "action", "Run to the action's time; act again", "InfraEngine.replay"],
        ["d3", "decision", "More actions?"],
        ["a6", "action", "Disruptions for the open faults", "InfrastructureSimulation._syncFaults"],
        ["e", "end"],
        ["f", "flowfinal"],
      ],
      edges: [["s", "d1"], ["d1", "f", "no"], ["d1", "a1", "yes"], ["a1", "d2"], ["d2", "f", "no"], ["d2", "a2", "yes"], ["a2", "a3"], ["a3", "a4"], ["a4", "m1"], ["m1", "a5"], ["a5", "d3"], ["d3", "m1", "yes"], ["d3", "a6", "no"], ["a6", "e"]],
    }],
    events: {
      listens: [
        { name: "object.added", does: "the engine is rebuilt (its actions replayed)" },
        { name: "object.removed", does: "rebuilt" },
        { name: "object.changed", does: "rebuilt when an asset or the base changed" },
        { name: "clock.set", does: "the engine jumps to the new time" },
      ],
    },
    parameters: [{ key: "display", default: "known condition, labels of faults", meaning: "What the layout shows: known or true condition, labels." }],
    rules: ["Engine time = offset + day × 1440 + the clock's minutes.", "A van drives the streets at 30 km/h, then walks at 1.2 m/s; 2 min to get ready."],
  },
];
