/**
 * Models of the architecture page: the journeys (travellers with travel plans). See ../model.js.
 * @module architecture/models/journeys
 */
export const JOURNEYS = [{
  id: "journeys", group: "journeys", title: "Journeys: travellers with travel plans",
  summary: "Hand-made travellers, each with a start, an aim and a chosen plan (walks, buses, trains with a change), follow it through the passenger simulation; their trains come from the journeys' timetable or from the rail operations.",
  description: "The planner works in clock minutes: walks over the sidewalks, bus connections of the bus lines (direct or with one change), trains of the timetable direct or with one change at the station, keeping the transfer time. A traveller waits at the stop as a passenger that only takes its line (or its train), rides in the bus's riders or on the train, and beyond the layout along the timetable. A missed or cancelled train: the next one of the same line. Without rail operations the journeys run the trains at the platforms themselves (TimetableRail as the services' planner); with them, OperationsRail reads the operations' trips.",
  files: ["web/arail/journeys/index.js", "web/arail/journeys/rail.js", "web/arail/journeys/planner.js", "web/arail/journeys/simulation.js", "web/app/journeys.js"],
  classes: [
    {
      name: "JourneysSimulation", file: "web/arail/journeys/simulation.js", kind: "class", extends: "Simulation", role: "The travellers; as the services' planner it also runs the trains.",
      attributes: ["travellers: Traveller[]", "planner: Planner", "selected: string | null — followed in the panel", "active: boolean — the layout's first journeys", "runsTrains: boolean — the services' planner"],
      operations: ["rail() — the operations' trips if they run, else its timetable", "plan(opts) — travel plans", "addTraveller(opts)", "status(t) — what it is doing, planned and expected arrival", "results()", "step(dt)", "claims(dock)", "statusLines(area) — boards", "_stepTraveller(t, now, dt)", "_boarded(e)", "_exited(e)", "_nextTrain(t, leg, after)", "pickables(view) — travellers walking and at their start", "describeAgent(t) — status, plan, arrival"],
    },
    {
      name: "Traveller", file: "web/arail/journeys/simulation.js", kind: "class", extends: "Person", role: "One traveller and its progress.",
      attributes: ["from: object — a building or a station", "to: object", "leave: number — clock minutes", "plan: object — legs, departure, arrival, transfers", "state: string — home, walking, waiting, bus, train, beyond, alighting, outside, arrived", "missed: number — trains missed or cancelled"],
      operations: ["reset(day)", "toJSON()"],
    },
    {
      name: "Planner", file: "web/arail/journeys/planner.js", kind: "class", role: "Travel plans in clock minutes.",
      operations: ["places() — buildings and stations", "plan(opts)", "walk(fromPoints, toPoints)", "_bus(fromPoints, toPoints, t)", "_trains(A, B, t, transfer)", "_departures(station, t0, t1)", "alightMin(area)"],
    },
    {
      name: "TimetableRail", file: "web/arail/journeys/rail.js", kind: "class", role: "The journeys' own timetable and its trains at the platforms.",
      attributes: ["days: Map — trips per day", "visits: Map — trains at the platforms"],
      operations: ["trips(day)", "tripOf(vehicle)", "expected(trip, station, kind)", "departedFrom(trip, station, now)", "step()", "_call(dockId, station, arrived, next, now)", "_stepVisit(visit, now, fx)", "_cancel(trip, station, now)", "statusLines(area)"],
    },
    { name: "OperationsRail", file: "web/arail/journeys/rail.js", kind: "class", role: "The rail operations' trips, read as the journeys' trips.", operations: ["trips(day)", "tripOf(vehicle)", "expected(trip, station, kind)"] },
    { name: "journeys", file: "web/arail/journeys/index.js", kind: "module", role: "Registration.", operations: ["journeysOf(world)", "registerJourneys(registry)"] },
    { name: "JourneysPanel", file: "web/app/journeys.js", kind: "class", role: "The Journeys tab: make a traveller, choose a plan, follow it, results.", operations: ["render(el)", "update()", "addJourneys()"] },
  ],
  relations: [
    { from: "JourneysSimulation", to: "Traveller", kind: "composes", label: "travellers *" },
    { from: "JourneysSimulation", to: "Planner", kind: "composes", label: "planner" },
    { from: "JourneysSimulation", to: "TimetableRail", kind: "composes", label: "_own" },
    { from: "JourneysSimulation", to: "OperationsRail", kind: "creates", label: "with rail operations" },
    { from: "OperationsRail", to: "OperationsSimulation", kind: "uses", label: "ops" },
    { from: "JourneysSimulation", to: "PassengerSimulation", kind: "uses", label: "enter, alight, release" },
    { from: "TimetableRail", to: "ServiceManager", kind: "uses", label: "call (mode plan)" },
    { from: "Planner", to: "Transit", kind: "uses", label: "connections" },
    { from: "JourneysPanel", to: "JourneysSimulation", kind: "uses" },
  ],
  activities: [
    {
      id: "traveller", name: "A traveller's journey",
      nodes: [
        ["s", "start"],
        ["a1", "action", "At its time it sets off", "JourneysSimulation._start"],
        ["m1", "merge"],
        ["d1", "decision", "Its next leg?"],
        ["a2", "action", "Walk over the sidewalks", "JourneysSimulation._walk"],
        ["a3", "action", "Onto the stop: a passenger that only takes its line or train", "JourneysSimulation._enter"],
        ["m2", "merge"],
        ["d2", "decision", "While it waits?"],
        ["a4", "action", "Its train stands at another platform: go over", "JourneysSimulation._checkPlatform"],
        ["a5", "action", "Its train cancelled or gone: the next of its line", "JourneysSimulation._nextTrain"],
        ["r1", "receive", "passenger.boarded"],
        ["a6", "action", "On board: in the bus's riders, or its train noted (missed++ if another)", "JourneysSimulation._boarded"],
        ["a7", "action", "Beyond the layout: its train leaves at the timetable's time", "JourneysSimulation._waitBeyond"],
        ["a8", "action", "Ride; get off at its stop, leave by the planned exit", "JourneysSimulation._exited"],
        ["a9", "action", "Arrived: planned and real arrival compared", "JourneysSimulation._finish"],
        ["x1", "send", "journeys.traveller.arrived"],
        ["e", "end"],
        ["f", "flowfinal"],
      ],
      edges: [["s", "a1"], ["a1", "m1"], ["m1", "d1"], ["d1", "a2", "walk"], ["d1", "a3", "bus, or a train from a platform"], ["d1", "a7", "a train from beyond"], ["d1", "a9", "none left"], ["a2", "m1"], ["a3", "m2"], ["m2", "d2"], ["d2", "a4", "another platform"], ["d2", "a5", "cancelled or gone"], ["d2", "r1", "its vehicle came"], ["a4", "m2"], ["a5", "m2"], ["r1", "a6"], ["a6", "a8"], ["a7", "a8", "departed"], ["a7", "f", "no more trains"], ["a8", "m1"], ["a9", "x1"], ["x1", "e"]],
    },
    {
      id: "trains", name: "The journeys' trains at the platforms (TimetableRail.step)",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Trips of today ± a day; the effects at each station", "TimetableRail.step"],
        ["m1", "merge"],
        ["d1", "decision", "A train due to arrive?"],
        ["d2", "decision", "Cancelled, closed, held, or no free track?"],
        ["a2", "action", "Cancelled", "TimetableRail._cancel"],
        ["x1", "send", "vehicle.cancelled"],
        ["a3", "action", "Held outside: later", "TimetableRail.step"],
        ["a4", "action", "Called to a track of its line (mode plan); it waits", "TimetableRail._call"],
        ["a5", "action", "Trains starting here come out of the sidings shortly before they leave", "TimetableRail.step"],
        ["a6", "action", "Each train at a platform", "TimetableRail._stepVisit"],
        ["d3", "decision", "Time to leave, nobody getting on (≤ 30 s), not held?"],
        ["a7", "action", "Departs; turns round or goes to the sidings", "TimetableRail._stepVisit"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "m1"], ["m1", "d1"], ["d1", "d2", "yes"], ["d2", "a2", "cancelled or closed"], ["d2", "a3", "held, no track"], ["d2", "a4", "no"], ["a2", "x1"], ["x1", "m1"], ["a3", "m1"], ["a4", "m1"], ["d1", "a5", "no"], ["a5", "a6"], ["a6", "d3"], ["d3", "a7", "yes"], ["d3", "e", "not yet"], ["a7", "e"]],
    },
    {
      id: "plan", name: "Travel plans (Planner.plan)",
      nodes: [
        ["s", "start"],
        ["d1", "decision", "Start and aim known, and different?"],
        ["d2", "decision", "Both buildings?"],
        ["a1", "action", "On foot", "Planner.plan"],
        ["a2", "action", "Buses: direct, else one change", "Planner._bus"],
        ["m1", "merge"],
        ["a3", "action", "Trains: departures within 6 h after getting to the platform plus the transfer time", "Planner._departures"],
        ["a4", "action", "Direct trains, and one change at the station (alighting, walk, transfer time)", "Planner._trains"],
        ["a5", "action", "Ranked by arrival, changes, walking; at most 6", "choose"],
        ["e", "end"],
        ["f", "flowfinal"],
      ],
      edges: [["s", "d1"], ["d1", "f", "no: no plan"], ["d1", "d2", "yes"], ["d2", "a1", "yes"], ["a1", "a2"], ["a2", "m1"], ["d2", "m1", "no"], ["m1", "a3"], ["a3", "a4"], ["a4", "a5"], ["a5", "e"]],
    },
  ],
  parameters: [
    { key: "transfer_min", default: "3", meaning: "The least time a new plan keeps between getting to a platform (or off a vehicle) and the next train (clock min).", sim: "journeys" },
    { key: "stations, lines", default: "from the platforms' lines", meaning: "The timetable, in the format of the rail operations." },
    { key: "travellers", default: "[]", meaning: "The travellers of an exercise, kept with the layout." },
  ],
  events: {
    emits: [
      { name: "journeys.traveller.added", payload: "simulation, traveller", when: "a traveller is made" },
      { name: "journeys.traveller.arrived", payload: "simulation, traveller, delay", when: "a traveller arrives" },
      { name: "vehicle.cancelled", payload: "vehicle, dock, area", when: "a train of its timetable is cancelled" },
    ],
    listens: [
      { name: "passenger.boarded", does: "a traveller got on" },
      { name: "passenger.exited", does: "a traveller left the stop: next leg, or outside" },
      { name: "passenger.removed", does: "taken off the stop: back to it" },
      { name: "vehicle.arrived", does: "riders of a bus get off at their stop" },
      { name: "clock.set", does: "travellers whose time is still ahead start again" },
    ],
  },
  rules: [
    "World time = clock minutes since 00:00 of day 0; a trip's id is day:line:direction:number.",
    "It runs the trains only without rail operations (it is then the services' planner, its tracks in mode plan).",
    "Trains come out of the sidings 4 min before they leave (at least 20 simulated s), wait up to 30 s for people getting on, turn round within 20 min or go to the sidings.",
    "Walking 1.3 m/s; stops within 450 m; buses at 55 % of their speed plus 12 s per stop.",
  ],
}];
