/**
 * Models of the architecture page: rail operations. See ../model.js for the format.
 * @module architecture/models/operations
 */
export const OPERATIONS = [
  {
    id: "ops-engine", group: "operations", title: "The operations engine: timetable and dispatching",
    summary: "A discrete-event simulation of a railway undertaking: each day's trips, rotations and duties, and every departure decided: go, wait, run short or cancel.",
    description: "OpsEngine pops events from a heap in minutes since day 0. Each day it builds the trips from the lines (every takt from first to last), the rotations of the units (Umläufe) and the pieces of the crews' duties; the dispatcher then decides each departure from the units' ETAs and the driver's readiness. Its random numbers are streams keyed by what they decide (a unit and a trip, a person and a day), so the same seed gives the same failures and sick calls in every setup of a comparison.",
    files: ["web/arail/ops/engine.js", "web/arail/ops/util.js", "web/arail/ops/timetable.js", "web/arail/ops/config.js", "web/arail/ops/index.js"],
    classes: [
      {
        name: "OpsEngine", file: "web/arail/ops/engine.js", kind: "class", role: "Event loop and dispatcher; owns the units, the workshop's bays, the crew desk and the ledger.",
        attributes: ["model: object — the normalized settings", "queue: EventQueue", "now: number — engine minutes", "trips: Map", "units: Map — Unit by id", "desk: CrewDesk", "ledger: Ledger", "daily: Map — counters per day"],
        operations: ["runTo(t)", "runDays(n)", "_handle(e)", "_prepareDay(d)", "_tryDepart(trip) — go, wait or cancel", "_unitsFor(trip)", "_depart(trip, units, driver, conductor, short, shortCauses)", "_arrive(trip, token)", "_cancel(trip, cause, opts)", "inject(event) — a disruption or stress event", "emit(name, payload)", "on(fn)"],
      },
      { name: "EventQueue", file: "web/arail/ops/util.js", kind: "class", role: "A binary heap by time, priority, sequence (also used by the infrastructure).", attributes: ["items: object[] — {t, prio, seq, type, data}"], operations: ["push(t, type, data, prio)", "pop()", "peekTime()"] },
      { name: "timetable", file: "web/arail/ops/timetable.js", kind: "module", role: "A day's trips, rotations and crew pieces.", operations: ["tripTemplates(model, wd) — out and back every takt", "planRotations(model, trips, depot)", "planPieces(model, rotations, tripsByKey, relief, base, depot)", "dayKind(model, wd)"] },
      { name: "config", file: "web/arail/ops/config.js", kind: "module", role: "Defaults, the network from the platforms, validation, presets.", attributes: ["OPS_DEFAULTS"], operations: ["normalizeOps(config, layout)", "autoNetwork(layout) — lines from the platforms' line names", "validateOps(cfg, layout)"] },
      { name: "util", file: "web/arail/ops/util.js", kind: "module", role: "Time, working hours, random streams.", attributes: ["DAY — 1440 minutes"], operations: ["stream(seed, ...parts) — random numbers per key", "lognormal(rng, median, sigma)", "isOpen(hours, t, startWeekday)", "nextOpen(hours, t, startWeekday)"] },
    ],
    relations: [
      { from: "OpsEngine", to: "EventQueue", kind: "composes", label: "queue" },
      { from: "OpsEngine", to: "Unit", kind: "composes", label: "units *" },
      { from: "OpsEngine", to: "CrewDesk", kind: "composes", label: "desk" },
      { from: "OpsEngine", to: "Ledger", kind: "composes", label: "ledger" },
      { from: "OpsEngine", to: "timetable", kind: "depends" },
      { from: "OpsEngine", to: "config", kind: "depends" },
    ],
    activities: [
      {
        id: "loop", name: "The event loop: run to a time",
        nodes: [
          ["s", "start"],
          ["m1", "merge"],
          ["d1", "decision", "An event due by then?"],
          ["a1", "action", "Pop the earliest; now = its time", "OpsEngine.runTo"],
          ["d2", "decision", "Its kind?"],
          ["a2", "action", "A new day: trips, roster, units to rotations", "OpsEngine._prepareDay"],
          ["a3", "action", "Maintenance planning", "OpsEngine._planRun"],
          ["a4", "action", "Dispatching: pull-outs, departures, arrivals, failures", "OpsEngine._tryDepart"],
          ["a5", "action", "ECM and the workshop: jobs, releases", "OpsEngine._jobCheck"],
          ["a6", "action", "Crews: sign on, sick calls, sign off", "CrewDesk.arrive"],
          ["a7", "action", "Samples, stress events, the day's end", "OpsEngine._handle"],
          ["m2", "merge"],
          ["a8", "action", "now = the time asked for", "OpsEngine.runTo"],
          ["e", "end"],
        ],
        edges: [["s", "m1"], ["m1", "d1"], ["d1", "a1", "yes"], ["d1", "a8", "no"], ["a1", "d2"], ["d2", "a2", "day"], ["d2", "a3", "plan"], ["d2", "a4", "trip, unit"], ["d2", "a5", "job"], ["d2", "a6", "crew"], ["d2", "a7", "other"], ["a2", "m2"], ["a3", "m2"], ["a4", "m2"], ["a5", "m2"], ["a6", "m2"], ["a7", "m2"], ["m2", "m1"], ["a8", "e"]],
      },
      {
        id: "trip", name: "A trip from dispatch to arrival",
        nodes: [
          ["s", "start"],
          ["m1", "merge"],
          ["a1", "action", "The station held or closed?", "OpsEngine._stationFx", "dispatcher"],
          ["a2", "action", "The planned driver, or a substitute", "CrewDesk.crewFor", "crew desk"],
          ["a3", "action", "The units' ETAs; a spare from the depot", "OpsEngine._unitsFor", "dispatcher"],
          ["d1", "decision", "Cancel, wait or go?"],
          ["a4", "action", "Wait and try again", "OpsEngine._wait", "dispatcher"],
          ["a5", "action", "A unit may fail to start", "OpsEngine._startFailure", "units"],
          ["a6", "action", "Depart (short if units are missing)", "OpsEngine._depart"],
          ["x1", "send", "ops.trip.departed"],
          ["d2", "decision", "On the way?"],
          ["a7", "action", "A defect: extra delay", "OpsEngine._softFailure", "units"],
          ["a8", "action", "A breakdown: limp on, or stranded and towed", "OpsEngine._hardFailure", "units"],
          ["a9", "action", "Arrive: km run, the units' next use, the crew free", "OpsEngine._arrive"],
          ["a10", "action", "Cancel it (and the rest of the crew's piece)", "OpsEngine._cancel", "dispatcher"],
          ["a11", "action", "Book the incident: penalties down the contracts", "Ledger.book", "ledger"],
          ["e", "end"],
        ],
        edges: [["s", "m1"], ["m1", "a1"], ["a1", "a2"], ["a2", "a3"], ["a3", "d1"], ["d1", "a10", "closed, no driver or unit in time"], ["d1", "a4", "held, a little late"], ["d1", "a5", "go"], ["a4", "m1"], ["a5", "a6"], ["a6", "x1"], ["x1", "d2"], ["d2", "a7", "defect"], ["d2", "a8", "failure"], ["d2", "a9", "arrived"], ["a7", "d2"], ["a8", "d2", "limps on"], ["a8", "a11", "stranded"], ["a9", "a11", "late"], ["a9", "e", "on time"], ["a10", "a11"], ["a11", "e"]],
      },
    ],
    parameters: [
      { key: "lines", default: "from the platforms' line names", meaning: "Route, takt_min 60, first 05:00, last 23:00, turn_min 8, units, peak units." },
      { key: "dispatch", default: "wait_unit_min 20, wait_crew_min 15, short_wait_min 5", meaning: "How long the dispatcher waits before running short or cancelling." },
      { key: "burn_in_days", default: "7", meaning: "Days run quietly before the clock's day." },
      { key: "delays", default: "p 0.1, median 2.5 min, σ 0.8, max 45 min", meaning: "Primary delays." },
    ],
    events: {
      emits: [
        { name: "ops.trip.departed", payload: "trip", when: "a trip leaves" },
        { name: "ops.trip.cancelled", payload: "trip, cause", when: "a trip is cancelled" },
        { name: "ops.penalty", payload: "entry", when: "the ledger books an entry (Ledger.onEntry)" },
        { name: "ops.day.end", payload: "day", when: "04:00 after an operating day" },
      ],
    },
    rules: [
      "Event priorities on a tie: start 1, arrival 2, crew 3, pull-out 4, work 5, departure 6, end 8, close 9.",
      "Cancel if the driver is not ready by departure + wait_crew_min or the first unit's ETA is after departure + wait_unit_min; missing units are awaited short_wait_min, then the train runs short.",
      "Run time = planned + primary delay + defect delay − recovery (≤ 1 min).",
      "A spare unit: at the depot, ready, released, not overdue, no job within 180 min; the one with the most km left.",
    ],
  },
  {
    id: "ops-fleet", group: "operations", title: "Units, maintenance (ECM) and the workshop",
    summary: "Units wear with every km and fail by an age- and wear-dependent hazard; the four ECM functions plan, develop, manage and deliver maintenance; the workshop works in its hours.",
    files: ["web/arail/ops/fleet.js", "web/arail/ops/engine.js"],
    classes: [
      {
        name: "Unit", file: "web/arail/ops/fleet.js", kind: "class", role: "One multiple unit.",
        attributes: ["km: number — odometer", "counters: object — km and time since each maintenance level", "wear: number — km since the last reset", "defects: object[]", "status: string", "released: boolean"],
        operations: ["run(km, t)", "usage(level, t, km)", "mostDue(program, t, km)", "overdue(program, t)", "kmLeft(program, t, km)", "maintained(level, program, t, quality)"],
      },
      { name: "fleet", file: "web/arail/ops/fleet.js", kind: "module", role: "The failure model.", attributes: ["UNIT_STATES"], operations: ["expectedFailures(unit, km, kind, opts)", "wearInterval(program)"] },
    ],
    relations: [
      { from: "OpsEngine", to: "Unit", kind: "composes", label: "units *" },
      { from: "Unit", to: "fleet", kind: "depends" },
    ],
    activities: [{
      id: "cycle", name: "A unit's maintenance cycle",
      nodes: [
        ["s", "start"],
        ["m0", "merge"],
        ["a1", "action", "Run trips: km, wear", "Unit.run", "operator"],
        ["d1", "decision", "Failed, overdue, or a defect due?"],
        ["a2", "action", "Report to planning", "OpsEngine._report", "operator"],
        ["a3", "action", "Book the repair or the due job now", "OpsEngine._planRepair", "ECM 3 planning"],
        ["a4", "action", "Daily planning: levels due by the planner's km", "OpsEngine._planDay", "ECM 3 planning"],
        ["a5", "action", "A bay slot in the workshop's hours", "OpsEngine._book", "ECM 3 planning"],
        ["d2", "decision", "Slot before the limit?"],
        ["a6", "action", "Ask development for an extension", "OpsEngine._requestExtension", "ECM 2 development"],
        ["m1", "merge"],
        ["m2", "merge"],
        ["a7", "action", "At the depot, order and parts in, bay free?", "OpsEngine._jobCheck", "ECM 4 workshop"],
        ["d3", "decision", "Can start?"],
        ["a8", "action", "Work, with spread and findings", "OpsEngine._jobCheck", "ECM 4 workshop"],
        ["a9", "action", "Counters and wear reset; late release counted", "OpsEngine._jobEnd", "ECM 4 workshop"],
        ["a10", "action", "The release reaches the operator", "OpsEngine._release", "ECM 1 management"],
      ],
      edges: [["s", "m0"], ["m0", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "a4", "no, at planning time"], ["a2", "a3"], ["a3", "m2"], ["a4", "a5"], ["a5", "d2"], ["d2", "m1", "yes"], ["d2", "a6", "no"], ["a6", "m1"], ["m1", "m2", "at the planned start"], ["m2", "a7"], ["a7", "d3"], ["d3", "a7", "no: check again"], ["d3", "a8", "yes"], ["a8", "a9"], ["a9", "a10"], ["a10", "m0"]],
    }],
    parameters: [
      { key: "failure", default: "hard 1.6 per 100 000 km, soft 2 per 10 000 km, wear share 0.6, shape 2", meaning: "The failure model." },
      { key: "program", default: "IS1 7 500 km / 21 d; IS2 30 000 km / 90 d; IS3 120 000 km / 365 d", meaning: "Maintenance levels and their limits (tolerance 10 %)." },
      { key: "workshop", default: "2 bays, 24/7, quality 0.9", meaning: "The workshop." },
      { key: "ecm", default: "all functions with the railway undertaking", meaning: "Which party does which ECM function (integrated or distributed)." },
    ],
    events: {
      emits: [
        { name: "ops.unit.failed", payload: "unit, trip", when: "a unit fails in service" },
        { name: "ops.job.planned", payload: "job, unit", when: "maintenance planned" },
        { name: "ops.unit.released", payload: "unit, job", when: "back in service" },
      ],
    },
    rules: [
      "P(failure on a trip) = 1 − e^(−rate · km · A · W); A = 1 + infant · e^(−age/1 y) + ageing · max(0, age − 12 y); W from the wear since the last maintenance (Weibull shape 2).",
      "No service if the usage exceeds 1 + tolerance + extension, or a defect is past its deadline.",
      "Messages between parties are delivered within their working hours plus latency (distributed ECM: a day's data latency).",
    ],
  },
  {
    id: "ops-crew", group: "operations", title: "Crews: duties, roster, sickness, the way to work",
    summary: "Duties keep the working-time rules and are rostered the day before; the crew desk handles sick calls, stand-by, call-ins, substitutes, rest times and the way to work.",
    files: ["web/arail/ops/crew.js", "web/arail/ops/crewdesk.js"],
    classes: [
      {
        name: "CrewDesk", file: "web/arail/ops/crewdesk.js", kind: "class", role: "Roster and dispatcher of the crews.",
        attributes: ["people: Map — the staff", "duties: Map"],
        operations: ["roster(day, duties)", "prepare(day, duties) — sickness, the way to work", "arrive(pid, dutyId, t) — sign on", "sickCall(pid, dutyId)", "cover(duty, cause, opts) — stand-by or call-in", "crewFor(trip, role)", "depart(trip, role, p, substitute)", "arrived(trip, role, t, lateCause)", "end(pid, dutyId, t) — sign off"],
      },
      { name: "crew", file: "web/arail/ops/crew.js", kind: "module", role: "Duties and staff.", attributes: ["WORK_RULES — 6 h without a break at most; 30 / 45 min breaks"], operations: ["buildDuties(model, pieces, opts)", "reserveDuties(model, role)", "makeStaff(model, count, opts)", "commuteOf(model, home)"] },
    ],
    relations: [
      { from: "CrewDesk", to: "Person", kind: "aggregates", label: "people *" },
      { from: "CrewDesk", to: "OpsEngine", kind: "uses", label: "e" },
      { from: "crew", to: "Population", kind: "uses", label: "names" },
    ],
    activities: [{
      id: "day", name: "A driver's day",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Rostered at noon the day before", "CrewDesk.roster", "roster"],
        ["d1", "decision", "Somebody fits the duty?"],
        ["a2", "action", "Sickness and vacation drawn", "CrewDesk.prepare", "roster"],
        ["d2", "decision", "Sick today?"],
        ["a3", "action", "A sick call before signing on", "CrewDesk.sickCall", "driver"],
        ["x1", "send", "ops.crew.sick"],
        ["a4", "action", "Stand-by, a call-in, or the duty stays open", "CrewDesk.cover", "dispatcher"],
        ["m1", "merge"],
        ["a5", "action", "The way to work: on foot, by car or by train", "CrewDesk._planCommute", "driver"],
        ["a6", "action", "Sign on (maybe late)", "CrewDesk.arrive", "driver"],
        ["x2", "send", "ops.crew.signon"],
        ["m2", "merge"],
        ["a7", "action", "The planned driver ready, else a substitute", "CrewDesk.crewFor", "dispatcher"],
        ["a8", "action", "Drive the trip; free at the station or the base", "CrewDesk.arrived", "driver"],
        ["d3", "decision", "Pieces left?"],
        ["a9", "action", "Sign off; the rest before the next duty", "CrewDesk.end", "driver"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "m2", "no: the duty is open"], ["a2", "d2"], ["d2", "a3", "yes"], ["d2", "m1", "no"], ["a3", "x1"], ["x1", "a4"], ["a4", "m1", "a replacement"], ["a4", "m2", "nobody"], ["m1", "a5"], ["a5", "a6"], ["a6", "x2"], ["x2", "m2"], ["m2", "a7"], ["a7", "a8"], ["a8", "d3"], ["d3", "m2", "yes"], ["d3", "a9", "no"], ["a9", "e"]],
    }],
    parameters: [
      { key: "crew", default: "staffing 1.05, sick_rate 0.06, sick_days 4, vacation_rate 0.08, stand-by 04:15–12:15 and 12:00–20:00", meaning: "The staff and their absences." },
      { key: "contracts", default: "full time 70 % (38 h, ≤ 10 h a duty, 11 h rest), part time 30 %", meaning: "Contracts and their rules." },
      { key: "commute", default: "margin 10 min, late p 0.03, car 25 min", meaning: "The way to work." },
    ],
    events: {
      emits: [
        { name: "ops.crew.signon", payload: "person, duty", when: "a driver signs on" },
        { name: "ops.crew.sick", payload: "person, duty", when: "a sick call" },
      ],
    },
    rules: [
      "A duty: at most 360 min without a break of 15 min or more; more than 6 h of work needs 30 min of breaks, more than 9 h 45 min.",
      "Staff = ⌈max(hours / hours a week, duties / days) / (1 − vacation − sickness) × staffing⌉.",
      "A sick spell starts with p = sick_rate / (sick_days × (1 − sick_rate)).",
      "A substitute when the planned driver is more than short_wait_min late; a duty may run 30 min over its limit.",
    ],
  },
  {
    id: "ops-contracts", group: "operations", title: "Parties and penalties",
    summary: "Every incident has a cause, every cause a responsible party; the operator pays the transport authority and claims along the chain of contracts.",
    files: ["web/arail/ops/contracts.js"],
    classes: [
      { name: "Ledger", file: "web/arail/ops/contracts.js", kind: "class", role: "The penalty ledger.", attributes: ["parties: Map", "entries: object[] — {t, contract, payer, payee, amount, type, cause}"], operations: ["responsible(cause)", "path(party) — the contracts from the operator to a party", "book(inc)"] },
      { name: "contracts", file: "web/arail/ops/contracts.js", kind: "module", role: "Causes and amounts.", attributes: ["CAUSE_FUNCTION — cause → ECM function or party", "AUTHORITY_TYPES"], operations: ["authorityAmount(p, inc)", "itemAmount(p, inc)"] },
    ],
    relations: [{ from: "Ledger", to: "contracts", kind: "depends" }, { from: "OpsEngine", to: "Ledger", kind: "composes", label: "ledger" }],
    parameters: [
      { key: "contracts.transport", default: "12 €/km cancelled, 40 € a late trip (≥ 5 min), 4 €/km per missing unit", meaning: "The operator pays the authority." },
      { key: "contracts.availability", default: "2 500 € a missing unit, 1 200 € a hard failure", meaning: "The ECM pays the operator." },
    ],
    rules: ["Crew, commute, sickness, rest, primary delays, capacity → the operator; failures and defects → ECM management; overrun, repeat failures → the workshop; release, planning, overdue → planning; infrastructure and external causes → nobody.", "Each contract on the path passes on a share (0.5) of what it pays, plus its own items."],
  },
  {
    id: "ops-experiment", group: "operations", title: "Comparing setups under stress tests",
    summary: "Runs each setup (integrated or distributed ECM, crew buffers …) under a stress test for days and several seeds without the clock, and compares the key figures.",
    files: ["web/arail/ops/experiment.js", "web/arail/ops/config.js", "tools/ops-compare.mjs"],
    classes: [
      { name: "experiment", file: "web/arail/ops/experiment.js", kind: "module", role: "Comparisons.", attributes: ["KPIS — 24 key figures"], operations: ["runExperiment(opts) — an async generator", "runOne(config, opts)", "kpis(engine, opts)", "summarize(results, opts)", "toCSV(result)"] },
      { name: "config", file: "web/arail/ops/config.js", kind: "module", role: "Presets.", attributes: ["PRESET_SETUPS", "PRESET_STRESS"], operations: ["applySetup(config, setup, stress)", "setupsOf(config)", "stressOf(config)"] },
    ],
    relations: [{ from: "experiment", to: "OpsEngine", kind: "creates", label: "per setup and seed" }, { from: "experiment", to: "config", kind: "depends" }],
    activities: [{
      id: "compare", name: "Comparing setups under a stress test",
      nodes: [
        ["s", "start"],
        ["m1", "merge"],
        ["a1", "action", "The next setup and seed", "runExperiment"],
        ["a2", "action", "Settings with the setup's and the stress test's patches", "applySetup"],
        ["a3", "action", "An engine; burn-in days", "runOne"],
        ["a4", "action", "The stress test's events", "OpsEngine.scheduleStress"],
        ["a5", "action", "Run the measured days", "runOne"],
        ["a6", "action", "Key figures", "kpis"],
        ["d1", "decision", "More runs?"],
        ["a7", "action", "Mean, min, max; per party; per day", "summarize"],
        ["a8", "action", "CSV", "toCSV"],
        ["e", "end"],
      ],
      edges: [["s", "m1"], ["m1", "a1"], ["a1", "a2"], ["a2", "a3"], ["a3", "a4"], ["a4", "a5"], ["a5", "a6"], ["a6", "d1"], ["d1", "m1", "yes"], ["d1", "a7", "no"], ["a7", "a8"], ["a8", "e"]],
    }],
    parameters: [
      { key: "days, seeds", default: "28, [1, 2, 3] (the app: 14 days, 3 runs)", meaning: "Length and repetitions." },
      { key: "setups", default: "as configured, integrated, distributed, full service, crew buffers, lean crew", meaning: "What is compared." },
      { key: "stress", default: "none, flu, shortage, heat, bus strike, slow workshop, bad Monday, unit damage", meaning: "What it is compared under." },
    ],
    rules: ["Cancelled share = (cancelled + terminated) / trips; MDBF = km run / hard failures.", "The same seed gives the same draws per unit and trip, per person and day, in every setup."],
  },
  {
    id: "ops-world", group: "operations", title: "Rail operations on the layout",
    summary: "The engine on the world's clock: its trains at the platforms (docks in mode plan), the boards, crews walking to the depot, the depot's units, the Operations tab.",
    files: ["web/arail/ops/simulation.js", "web/arail/ops/depot.js", "web/arail/ops/disruptions.js", "web/arail/ops/index.js", "web/app/operations.js"],
    classes: [
      {
        name: "OperationsSimulation", file: "web/arail/ops/simulation.js", kind: "class", extends: "Simulation", role: "The engine in the world; the services' planner of its platforms.",
        attributes: ["engine: OpsEngine", "visits: Map — trains at the platforms", "walkers: object[] — crews walking", "active: boolean — the layout's first operations"],
        operations: ["step(dt)", "_ensure() — rebuilt when stations, lines or settings change", "_clockJump()", "_event(name, payload) — engine events to the world (ops.*)", "_stationFx(stationId)", "_stepVisits()", "_stepWalkers(dt)", "tripsAt(dockId)", "claims(dock)", "statusLines(area)"],
      },
      { name: "Depot", file: "web/arail/ops/depot.js", kind: "class", extends: "BuildingBase", role: "The depot: the workshop's bays and the stabled units; its door is the crews' base.", operations: ["draw(view)"] },
    ],
    relations: [
      { from: "OperationsSimulation", to: "OpsEngine", kind: "composes", label: "engine" },
      { from: "OperationsSimulation", to: "ServiceManager", kind: "uses", label: "call (mode plan)" },
      { from: "Depot", to: "OperationsSimulation", kind: "uses", label: "depotState" },
      { from: "OperationsPanel", to: "OperationsSimulation", kind: "uses" },
    ],
    activities: [{
      id: "step", name: "Rail operations in a world step",
      nodes: [
        ["s", "start"],
        ["d1", "decision", "The layout's first operations, enabled?"],
        ["a1", "action", "Rebuild the engine if stations, lines or settings changed", "OperationsSimulation._ensure"],
        ["d2", "decision", "The clock set back, or more than 30 min ahead?"],
        ["a2", "action", "Catch up quietly (never backwards)", "OperationsSimulation._clockJump"],
        ["a3", "action", "Run the engine to the clock", "OpsEngine.runTo"],
        ["a4", "action", "Its trains at the platforms", "OperationsSimulation._stepVisits"],
        ["a5", "action", "Crews walk; their arrival to the engine", "OperationsSimulation._stepWalkers"],
        ["e", "end"],
      ],
      edges: [["s", "d1"], ["d1", "e", "no"], ["d1", "a1", "yes"], ["a1", "d2"], ["d2", "a2", "yes"], ["d2", "a3", "no"], ["a2", "e"], ["a3", "a4"], ["a4", "a5"], ["a5", "e"]],
    }],
    events: {
      emits: [{ name: "vehicle.cancelled", payload: "vehicle, dock, area", when: "a train of its timetable is cancelled shortly before it leaves" }],
      listens: [
        { name: "clock.set", does: "the engine jumps ahead (never backwards)" },
        { name: "object.added", does: "the stations may have changed" },
        { name: "object.removed", does: "the stations may have changed" },
        { name: "object.changed", does: "the stations may have changed" },
      ],
    },
    rules: ["Engine time = (burn-in days + the clock's day + shift) × 1440 + the clock's minutes.", "One per layout: the first one is the services' planner; another stays idle."],
  },
];
