/**
 * Models of the architecture page: the container terminal. See ../model.js for the format.
 * @module architecture/models/terminal
 */
export const TERMINAL = [
  {
    id: "terminal-model", group: "terminal", title: "Containers, carriers and the inventory",
    summary: "The terminal's rules without the world: container sizes and codes, carrier types, and the inventory with its stacking rules and reservations.",
    description: "Every check returns a sentence that says why not (shown in the Terminal tab), or null. Wagons, trucks, barges and yard blocks are carriers with bays, rows and tiers; a 40 or 45 ft container fills two bays. A move reserves its target cell, so no other move can use it.",
    files: ["web/arail/terminal/model.js"],
    classes: [
      {
        name: "Container", file: "web/arail/terminal/model.js", kind: "class", role: "One box; its id is its BIC code.",
        attributes: ["id: string — BIC code with check digit", "size: \"20\" | \"40\" | \"45\"", "high: boolean — high cube", "at: object | null — its slot", "handler: string | null — the machine carrying it", "move: string | null — its move"],
        operations: ["length_m — getter", "teu — getter", "toJSON()"],
      },
      {
        name: "Carrier", file: "web/arail/terminal/model.js", kind: "class", role: "A wagon, truck, barge or yard block.",
        attributes: ["id: string", "kind: string — wagon, truck, barge, yard", "type: object — bays, rows, tiers, sizes", "pose: object | null — {center, heading}", "present: boolean — here", "available: boolean — may be handled"],
        operations: ["allows(size)", "firstBays(size)", "toLayout(along_m, across_m, scale)", "footprint(scale)"],
      },
      {
        name: "Inventory", file: "web/arail/terminal/model.js", kind: "class", role: "Who stands where; stacking, lifting, reservations.",
        attributes: ["carriers: Map", "containers: Map"],
        operations: ["add(container, ref)", "remove(containerId)", "canPlace(container, ref) — a reason or null", "canLift(container) — a reason or null", "freeSlots(container, carrierId)", "reserve(ref, size, moveId)", "release(moveId)", "detach(containerId, handlerId)", "attach(containerId, ref)", "check()"],
      },
      {
        name: "model", file: "web/arail/terminal/model.js", kind: "module", role: "Constants, carrier types, BIC codes.",
        attributes: ["CONTAINER_SIZES — 20, 40, 45 ft", "CARRIER_TYPES — sgns60, lgns40, sggrss80, chassis40", "BAY_M — 6.9 m"],
        operations: ["bicCheckDigit(code10)", "bicProblem(id)", "yardType(opts)", "bargeType(opts)"],
      },
    ],
    relations: [
      { from: "Inventory", to: "Carrier", kind: "aggregates", label: "carriers *" },
      { from: "Inventory", to: "Container", kind: "aggregates", label: "containers *" },
      { from: "Inventory", to: "model", kind: "depends" },
    ],
    activities: [{
      id: "place", name: "May a container go there? (Inventory.canPlace)",
      nodes: [
        ["s", "start"],
        ["d1", "decision", "A known place that takes this size?"],
        ["d2", "decision", "Bay, row and tier exist?"],
        ["d3", "decision", "Free and not reserved by another move?"],
        ["d4", "decision", "Something to stand on (tier above the ground)?"],
        ["a1", "action", "It may go there (no reason)", "Inventory.canPlace"],
        ["a2", "action", "The reason why not, as a sentence", "Inventory.canPlace"],
        ["m1", "merge"],
        ["e", "end"],
      ],
      edges: [["s", "d1"], ["d1", "d2", "yes"], ["d1", "a2", "no"], ["d2", "d3", "yes"], ["d2", "a2", "no"], ["d3", "d4", "yes"], ["d3", "a2", "no"], ["d4", "a1", "yes"], ["d4", "a2", "no"], ["a1", "m1"], ["a2", "m1"], ["m1", "e"]],
    }],
    rules: [
      "A cell is tier:row:bay; 40 and 45 ft containers fill a bay and the next.",
      "Reasons in this order: unknown place; size not taken; no such bay or row; stack too high; occupied; reserved; nothing to stand on (or a 40 ft box on a 20 ft one); already there.",
      "Lifting: not while another container (or a move that sets one) is on top.",
      "BIC check digit: letters A = 10, B = 12 … (multiples of 11 skipped), weight 2^i, sum mod 11 mod 10.",
    ],
  },
  {
    id: "terminal-objects", group: "terminal", title: "Terminal objects in Build",
    summary: "The objects of the group Terminal: yard blocks, gantry cranes, truck lanes, quays and reach stackers, whose geometry the simulation reads.",
    files: ["web/arail/terminal/objects.js", "web/arail/terminal/index.js"],
    classes: [
      { name: "GantryCrane", file: "web/arail/terminal/objects.js", kind: "class", extends: "LayoutObject", role: "A crane, its runway and its reach.", operations: ["toLocal(p)", "fromLocal(s, t)", "reaches(p)", "problems()"] },
      { name: "ContainerYard", file: "web/arail/terminal/objects.js", kind: "class", extends: "LayoutObject", role: "A yard block: bays × rows × tiers.", operations: ["carrierType()", "problems()"] },
      { name: "TruckLane", file: "web/arail/terminal/objects.js", kind: "class", extends: "LayoutObject", role: "Truck positions along a lane with a passing lane.", operations: ["at(s, offset)", "positions()", "problems()"] },
      { name: "Quay", file: "web/arail/terminal/objects.js", kind: "class", extends: "LayoutObject", role: "A fairway with the berth at its end.", operations: ["at(s, offset)", "problems()"] },
      { name: "ReachStacker", file: "web/arail/terminal/objects.js", kind: "class", extends: "LayoutObject", role: "The parking place of a reach stacker." },
      { name: "terminal", file: "web/arail/terminal/index.js", kind: "module", role: "Registers the terminal's types.", operations: ["registerTerminal(registry)"] },
    ],
    relations: [{ from: "terminal", to: "TerminalSimulation", kind: "depends", label: "registers" }],
    rules: ["Yard grid: bays = max(1, ⌊width / 6.9 m + 0.05⌋), rows likewise by 2.9 m.", "Truck positions 19 m apart around the lane's middle, at least 10 m from its ends.", "problems(): places no machine reaches, lanes too short or bending more than 10°, a berth out of reach."],
  },
  {
    id: "terminal-operations", group: "terminal", title: "The terminal at work",
    summary: "Moves from a request to done: checked, reserved, given to a free crane or reach stacker, carried through the machine's phases; trains, barges and trucks come and go.",
    description: "TerminalSimulation re-reads its objects whenever they, the marker map or the scale change, keeping its machines by object id. Each step it moves its trains, barges and trucks along their paths (a 1-D mover each), starts queued moves on idle machines whose carriers are ready, and advances the machines through their phases. Its random numbers are a stream of its own, so a terminal changes nothing in the other simulations. The Terminal tab and scenarios (terminal.request.* events) give it its work.",
    files: ["web/arail/terminal/operations.js", "web/arail/terminal/handlers.js", "web/arail/terminal/visits.js", "web/arail/terminal/movers.js", "web/arail/terminal/types.js", "web/arail/terminal/draw.js", "web/app/terminal.js"],
    classes: [
      {
        name: "TerminalSimulation", file: "web/arail/terminal/operations.js", kind: "class", extends: "Simulation", role: "The terminal: its moves, machines and visits.",
        attributes: ["inventory: Inventory", "moves: object[] — {id, container, from, to, handler, state, reason, waiting}", "handlers: Map — machines by object id", "visits: Map — trains, barges, trucks", "rolling: RollingStock | null — model wagons", "highlight: object — what the panel shows on the stage"],
        operations: ["request(containerId, to, opts) — a move", "targets(containerId) — where it may go", "call(visitId)", "depart(visitId, opts)", "sendTruck(opts)", "addTrain(opts)", "unload(visitId, opts)", "load(visitId, opts)", "cancel(moveId)", "observe(observations, time, opts) — tags of model wagons", "step(dt)", "saveStart()"],
      },
      {
        name: "HandlerBase", file: "web/arail/terminal/handlers.js", kind: "class", stereotype: "base class", role: "A machine: one move at a time, in eased phases.",
        attributes: ["phase: string — e.g. lowering, locking, lifting, carrying", "move: string | null", "load: Container | null"],
        operations: ["begin(move, container, host)", "step(dt, host)", "replan(host)", "abort()", "_setDown(host)"],
      },
      { name: "CraneHandler", file: "web/arail/terminal/handlers.js", kind: "class", extends: "HandlerBase", role: "A gantry crane: gantry, trolley, hoist.", operations: ["_plan(phase, host)", "_next(host)"] },
      { name: "StackerHandler", file: "web/arail/terminal/handlers.js", kind: "class", extends: "HandlerBase", role: "A reach stacker: drive, boom, hoist; parks when idle.", operations: ["_plan(phase, host)", "_next(host)"] },
      {
        name: "PathVisit", file: "web/arail/terminal/visits.js", kind: "class", stereotype: "base class", role: "A train or barge on its path.",
        attributes: ["state: string — away, approaching, positioned, departing", "carriers: Carrier[]", "mover: PathMover"],
        operations: ["call(host)", "depart(host)", "step(dt, host)"],
      },
      { name: "TrainVisit", file: "web/arail/terminal/visits.js", kind: "class", extends: "PathVisit", role: "Locomotive and wagons on a loading track." },
      { name: "BargeVisit", file: "web/arail/terminal/visits.js", kind: "class", extends: "PathVisit", role: "An inland barge at the quay; leaves astern." },
      { name: "TruckVisit", file: "web/arail/terminal/visits.js", kind: "class", role: "A truck with a chassis: pickup or delivery.", attributes: ["purpose: string — pickup or delivery", "state: string — waiting, approaching, positioned, departing"] },
      { name: "PathMover", file: "web/arail/terminal/movers.js", kind: "class", role: "A deterministic 1-D mover: accelerate, cruise, brake.", attributes: ["s: number — position along the path", "v: number — speed"], operations: ["setTarget(s)", "arrived()", "step(dt, opts)"] },
      { name: "visits", file: "web/arail/terminal/visits.js", kind: "module", role: "The truck lane's traffic.", operations: ["stepTrucks(trucks, lane, dt, host)", "departTruck(t, host)"] },
      { name: "TerminalPanel", file: "web/app/terminal.js", kind: "class", role: "The Terminal tab: moves from the panel and on the stage.", operations: ["render(el)", "update()", "addTerminal()"] },
    ],
    relations: [
      { from: "TerminalSimulation", to: "Inventory", kind: "composes", label: "inventory" },
      { from: "TerminalSimulation", to: "HandlerBase", kind: "composes", label: "handlers *" },
      { from: "TerminalSimulation", to: "PathVisit", kind: "composes", label: "visits *" },
      { from: "TerminalSimulation", to: "TruckVisit", kind: "composes", label: "visits *" },
      { from: "TerminalSimulation", to: "RollingStock", kind: "composes", label: "rolling 0..1" },
      { from: "PathVisit", to: "PathMover", kind: "composes", label: "mover" },
      { from: "CraneHandler", to: "GantryCrane", kind: "uses", label: "object" },
      { from: "StackerHandler", to: "ReachStacker", kind: "uses", label: "object" },
      { from: "TerminalPanel", to: "TerminalSimulation", kind: "uses" },
    ],
    activities: [
      {
        id: "move", name: "A move from request to done",
        nodes: [
          ["s", "start"],
          ["a1", "action", "May the container be lifted?", "TerminalSimulation._liftProblem"],
          ["d1", "decision", "Liftable?"],
          ["a2", "action", "The target slot; a machine that reaches both", "TerminalSimulation._resolve"],
          ["d2", "decision", "Slot and machine?"],
          ["a3", "action", "Reserve the target cell; queue the move", "TerminalSimulation._request"],
          ["x1", "send", "terminal.move.queued"],
          ["m1", "merge"],
          ["a4", "action", "Waiting for the carriers; reach checked again", "TerminalSimulation._dispatch"],
          ["d3", "decision", "Carriers ready, machine idle?"],
          ["a5", "action", "The machine begins", "HandlerBase.begin"],
          ["x2", "send", "terminal.move.started"],
          ["a6", "action", "Phases: lock (container leaves its slot) … set down (in its new one)", "HandlerBase.step"],
          ["d4", "decision", "Set down?"],
          ["a7", "action", "Release the reservation", "TerminalSimulation._finish"],
          ["x3", "send", "terminal.move.finished"],
          ["a8", "action", "Fail with a reason", "TerminalSimulation._fail"],
          ["x4", "send", "terminal.move.failed"],
          ["r1", "action", "Refused: the reason is shown", "TerminalSimulation.request"],
          ["e", "end"],
          ["f", "flowfinal"],
        ],
        edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "r1", "no"], ["a2", "d2"], ["d2", "a3", "yes"], ["d2", "r1", "no"], ["r1", "f"], ["a3", "x1"], ["x1", "m1"], ["m1", "a4"], ["a4", "d3"], ["d3", "m1", "no: next step"], ["d3", "a5", "yes"], ["a5", "x2"], ["x2", "a6"], ["a6", "d4"], ["d4", "a7", "yes"], ["d4", "a8", "no"], ["a7", "x3"], ["a8", "x4"], ["x3", "e"], ["x4", "e"]],
      },
      {
        id: "crane", name: "A crane's phases",
        nodes: [
          ["s", "start"],
          ["m1", "merge"],
          ["a1", "action", "Raise to the travel height; travel over the source", "CraneHandler._plan"],
          ["d1", "decision", "Off the source by more than 0.25 m?"],
          ["a2", "action", "Lower, lock; the container leaves its slot", "CraneHandler._next"],
          ["m2", "merge"],
          ["a3", "action", "Lift, carry over the target", "CraneHandler._plan"],
          ["d2", "decision", "Off the target by more than 0.25 m?"],
          ["a4", "action", "Set down; the container in its new slot", "HandlerBase._setDown"],
          ["a5", "action", "Release; the move is done", "CraneHandler._next"],
          ["e", "end"],
        ],
        edges: [["s", "m1"], ["m1", "a1"], ["a1", "d1"], ["d1", "m1", "yes: aim again"], ["d1", "a2", "no"], ["a2", "m2"], ["m2", "a3"], ["a3", "d2"], ["d2", "m2", "yes"], ["d2", "a4", "no"], ["a4", "a5"], ["a5", "e"]],
      },
      {
        id: "truck", name: "A truck's visit",
        nodes: [
          ["s", "start"],
          ["a1", "action", "A truck waits at the gate", "TerminalSimulation.sendTruck"],
          ["m1", "merge"],
          ["d1", "decision", "A position free and the entry clear?"],
          ["a2", "action", "Drive in on the passing lane, turn in", "stepTrucks"],
          ["x1", "send", "terminal.visit.arrived"],
          ["m2", "merge"],
          ["a3", "action", "Loaded or unloaded; ready for a few seconds", "TerminalSimulation._autoLeave"],
          ["d2", "decision", "Ready long enough?"],
          ["a4", "action", "Pull out when the lane is clear; drive off", "departTruck"],
          ["a5", "action", "Its containers leave the terminal", "TerminalSimulation._truckGone"],
          ["x2", "send", "terminal.visit.departed"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "m1"], ["m1", "d1"], ["d1", "m1", "no: wait"], ["d1", "a2", "yes"], ["a2", "x1"], ["x1", "m2"], ["m2", "a3"], ["a3", "d2"], ["d2", "m2", "no"], ["d2", "a4", "yes"], ["a4", "a5"], ["a5", "x2"], ["x2", "e"]],
      },
      {
        id: "train", name: "A train's or barge's visit",
        nodes: [
          ["s", "start"],
          ["a1", "action", "Called (Terminal tab or scenario)", "TerminalSimulation.call"],
          ["d1", "decision", "Path and place free?"],
          ["a2", "action", "Approach and stop at its place", "PathVisit.step"],
          ["x1", "send", "terminal.visit.arrived"],
          ["a3", "action", "Unload and load: moves queued", "TerminalSimulation._unload"],
          ["a4", "action", "Departure asked for", "TerminalSimulation.depart"],
          ["d2", "decision", "Moves of the visit still open?"],
          ["a5", "action", "Queued moves cancelled; leave when the active one is done", "TerminalSimulation.depart"],
          ["m1", "merge"],
          ["a6", "action", "Depart and leave", "PathVisit.depart"],
          ["x2", "send", "terminal.visit.departed"],
          ["e", "end"],
          ["f", "flowfinal"],
        ],
        edges: [["s", "a1"], ["a1", "d1"], ["d1", "f", "no: refused"], ["d1", "a2", "yes"], ["a2", "x1"], ["x1", "a3"], ["a3", "a4"], ["a4", "d2"], ["d2", "a5", "yes (forced)"], ["d2", "m1", "no"], ["a5", "m1"], ["m1", "a6"], ["a6", "x2"], ["x2", "e"]],
      },
    ],
    parameters: [
      { key: "trains", default: "[]", meaning: "Container trains: track, wagons, load, start (away or positioned)." },
      { key: "barges", default: "[]", meaning: "Inland barges: quay, length, tiers." },
      { key: "trucks.lane", default: "the first lane", meaning: "Where trucks come in." },
      { key: "containers, fill", default: "[], {}", meaning: "The start state: containers, and yards filled at random." },
      { key: "default_wagon", default: "sgns60", meaning: "Wagon type of trains without their own." },
    ],
    rules: [
      "Assignment: a crane that reaches both places with the fewest moves waiting, else the reach stacker nearest the source (wagon, truck or yard, within its tiers).",
      "Phase time: trapezoid(d, v, a) = 2√(d/a) if d ≤ v²/a, else d/v + v/a, scaled by the machine's speed; motion eased with smoothstep. Crane: gantry 1.5 m/s, trolley 1.2 m/s, hoist 0.8 m/s (loaded 0.5), lock 3 s.",
      "A move can be cancelled only before the lock; a box being carried goes back to its place, to its target, or to a free slot.",
      "Trucks wait at the gate while a moving truck is within 30 m of the entry; they leave 3 s after they are ready.",
    ],
  },
  {
    id: "rolling-stock", group: "terminal", title: "Model wagons from tags",
    summary: "Tags on model wagons, seen by the camera, become smoothed wagon poses on the tracks; the terminal's carriers follow them.",
    description: "The tracker lifts the tags to their height above the layout; RollingStock groups them by wagon number, fuses a wagon's tags into a pose, smooths and snaps it to a track, and keeps a wagon it no longer sees for a while. The terminal turns each wagon into a carrier W<n> that may be handled only while it stands.",
    files: ["web/arail/terminal/rolling.js", "web/arail/terminal/operations.js", "web/app/app.js"],
    classes: [
      {
        name: "RollingStock", file: "web/arail/terminal/rolling.js", kind: "class", role: "Tracks model wagons from their tags.",
        attributes: ["wagons: Map — number → {center, heading, state, speed, tags, lastSeen}", "stride: number — tags per wagon"],
        operations: ["observe(observations, time, opts)", "reset()", "_group(observations)", "_fuse(tags, previous)", "_update(w, measured, time, still, getTracks)", "_hold(w, time, visible)", "_snap(center, heading, tracks)"],
      },
      { name: "rolling", file: "web/arail/terminal/rolling.js", kind: "module", role: "Tag IDs.", attributes: ["ROLLING_DEFAULTS — hold 4 s, smoothing 0.15 s, snap 8 mm"], operations: ["decodeTag(id, stride)", "encodeTag(number, slot, stride)"] },
    ],
    relations: [
      { from: "TerminalSimulation", to: "RollingStock", kind: "composes", label: "rolling" },
      { from: "RollingStock", to: "rolling", kind: "depends" },
    ],
    activities: [{
      id: "observe", name: "Model wagons from one frame's tags",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Decode the tags; those of the wrong size dropped", "RollingStock._group"],
        ["m1", "merge"],
        ["a2", "action", "Fuse the tags of a wagon into a pose", "RollingStock._fuse"],
        ["d1", "decision", "A pose?"],
        ["a3", "action", "Smooth it; standing or moving", "RollingStock._update"],
        ["a4", "action", "Snap it to a track", "RollingStock._snap"],
        ["a5", "action", "Keep the known wagon (held)", "RollingStock._hold"],
        ["m2", "merge"],
        ["d2", "decision", "Another wagon?"],
        ["a6", "action", "Wagons hidden too long are lost", "RollingStock._hold"],
        ["a7", "action", "Carriers W<n> follow the wagons", "TerminalSimulation._syncWagons"],
        ["x1", "send", "terminal.wagon.lost"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "m1"], ["m1", "a2"], ["a2", "d1"], ["d1", "a3", "yes"], ["d1", "a5", "no"], ["a3", "a4"], ["a4", "m2"], ["a5", "m2"], ["m2", "d2"], ["d2", "m1", "yes"], ["d2", "a6", "no"], ["a6", "a7"], ["a7", "x1"], ["x1", "e"]],
    }],
    parameters: [{ key: "markers.rolling", default: "APRILTAG_36h11, 64 codes, 20 mm, 15 mm high, stride 4, 3 bit errors", meaning: "The tags of the model wagons and how they are read." }],
    rules: [
      "Tag ID = (wagon number − 1) × stride + slot; slot 0 at the A end.",
      "A wagon's centre from each tag; tags more than 6 mm from the median are dropped; with two tags or more the heading is a least-squares line.",
      "A jump of more than 30 mm or 45° starts the wagon anew; else smoothing 1 − e^(−dt/0.15 s); standing: under 3 mm/s for 1 s.",
      "A carrier is present unless its wagon is lost; available while it stands (or is held and stood).",
    ],
  },
];
