/**
 * Models of the architecture page: tracking the layout in camera frames, and the flyover's camera.
 * See ../model.js for the format.
 * @module architecture/models/tracking
 */
export const TRACKING = [
  {
    id: "detection", group: "tracking", title: "Marker detection",
    summary: "Finds the layout's markers, and the tags of model wagons, in one camera frame.",
    description: "On top of js-aruco2's candidates (adaptive threshold, contours) every candidate is kept, its corners are refined to sub-pixel accuracy, the centre of every code cell is sampled and the bits are decoded against the first codes of the dictionary, accepting only as many bit errors as keep chance matches rare. Without a chosen dictionary the dictionaries vote. Rolling-stock tags (AprilTag 36h11) are read from the same candidates; a candidate that reads in both families keeps the better reading.",
    files: ["web/arail/core/detector.js"],
    classes: [
      {
        name: "MarkerDetector", file: "web/arail/core/detector.js", kind: "class", role: "Decodes the candidates of a frame in the chosen (or voted) dictionary and in the tag family.",
        attributes: ["codes: number — IDs 0 … codes−1 are accepted", "det: AR.Detector — js-aruco2's candidate finder", "dictionaries: object[] — the dictionaries it knows", "rolling: object | null — the tag family of model wagons", "selected: object | null — the dictionary in use", "votes: object — votes per dictionary in automatic mode"],
        operations: ["detectAll(imageData, scale) — markers and tags of a frame", "detect(imageData, scale) — the markers", "setDictionary(name) — a dictionary, or null to vote", "_decodeEach(entry, candidates) — bits to IDs", "_arbitrate(entry, reads, rollingReads, lost) — a candidate read in both families", "_bestPerId(reads) — one detection per ID, the one with the fewest bit errors"],
      },
      {
        name: "detector", file: "web/arail/core/detector.js", kind: "module", role: "Sub-pixel corners, sampling the cells, the error correction.",
        attributes: ["DICTIONARIES — the seven dictionaries", "REFERENCE_CODES — 50 codes: the chance budget", "ROLLING_OPTIONS — AprilTag 36h11, 64 codes, 3 bit errors"],
        operations: ["refineCorners(g, w, h, corners) — fit lines to grey-value edges", "sampleCells(g, w, h, corners, n) — 3×3 samples per cell", "cellsToBits(cells, n) — Otsu threshold over the cells", "acceptedBitErrors(AR, name, codes, dict) — bit errors that can be corrected safely", "markerBits(AR, dictionaryName, id) — the bits of a marker (marker sheets)"],
      },
    ],
    relations: [
      { from: "MarkerDetector", to: "detector", kind: "depends" },
      { from: "App", to: "MarkerDetector", kind: "creates", label: "when the codes or tags change" },
    ],
    activities: [{
      id: "frame", name: "Detecting the markers of one frame",
      description: "MarkerDetector.detectAll on the frame drawn at its processing size.",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Grey image, adaptive threshold, contours: the candidates", "MarkerDetector.detectAll"],
        ["a2", "action", "Keep every candidate (also the inner outline of small markers)"],
        ["a3", "action", "Refine the corners; sample the cells; bits", "refineCorners"],
        ["d1", "decision", "Tags of model wagons wanted?"],
        ["a4", "action", "Decode the candidates as tags", "MarkerDetector._decodeEach"],
        ["m1", "merge"],
        ["d2", "decision", "Dictionary chosen?"],
        ["a5", "action", "Decode, settle candidates read in both families, best per ID", "MarkerDetector._arbitrate"],
        ["a6", "action", "Every dictionary decodes; the one with the most IDs gets a vote", "MarkerDetector._decodeEach"],
        ["a7", "action", "Six votes: that dictionary is chosen", "MarkerDetector.detectAll"],
        ["m2", "merge"],
        ["a8", "action", "Corners back to the frame's scale: markers and tags"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "a2"], ["a2", "a3"], ["a3", "d1"], ["d1", "a4", "yes"], ["d1", "m1", "no"], ["a4", "m1"], ["m1", "d2"], ["d2", "a5", "yes"], ["d2", "a6", "automatic"], ["a6", "a7"], ["a7", "m2"], ["a5", "m2"], ["m2", "a8"], ["a8", "e"]],
    }],
    parameters: [
      { key: "markers.dictionary", default: "auto", meaning: "The marker type of the layout (or voted)." },
      { key: "markers.codes", default: "50", meaning: "How many codes of the dictionary are used; a locked map: up to its highest ID." },
      { key: "markers.rolling", default: "none", meaning: "Tags of model wagons (AprilTag 36h11, 64 codes, 3 bit errors)." },
    ],
    rules: [
      "Corner refinement: an edge shorter than 8 px, fewer than 4 points per edge or a shift over 4 px keeps the corner as it was.",
      "3 × 3 samples per cell at ±0.22 of the cell; Otsu threshold over the cell means; low contrast (< 25) or a light border rejects the candidate.",
      "Accepted bit errors: ⌊(d − 1)/2⌋ + 1 of the code distance d; with fewer than 50 codes, no more than keeps chance matches as rare as with 50.",
      "A candidate read in both families: the lower share of bit errors wins, on a tie the layout's marker.",
      "Automatic dictionary: chosen at 6 votes; the tag family never votes.",
    ],
  },
  {
    id: "tracking", group: "tracking", title: "Marker map, pose and survey",
    summary: "Turns the markers of each frame into the layout's pose in the image, and measures unknown markers into the map.",
    description: "The marker map holds every marker's position on the layout. Each frame, the tracker measures unknown markers from known ones (survey), estimates one homography layout → image from all known markers (dropping outliers), smooths it, and keeps it for 1.5 s when no marker is seen. Moving markers (on vehicles) are reported, not used; rolling-stock tags are lifted to their height for the terminal. The app's video survey runs a tracker of its own over a video.",
    files: ["web/arail/core/tracker.js", "web/arail/core/geometry.js", "web/arail/core/camera.js", "web/app/survey.js"],
    classes: [
      {
        name: "MarkerMap", file: "web/arail/core/tracker.js", kind: "class", role: "Marker poses in the layout frame; locked and moving markers.",
        attributes: ["entries: Map — id → {x, y, theta, fixed}", "size: number — marker edge in mm", "locked: boolean — a complete map: nothing is surveyed", "moving: Set — markers on vehicles", "version: number — changes with every change", "generation: number — changes when the map is configured anew"],
        operations: ["configure(markers) — size, sizes, poses, origin, locked, moving from the layout file", "set(id, pose, fixed)", "lock()", "unlock()", "setMoving(ids)", "cornersInLayout(id)", "rebase(id) — another origin", "toJSON()"],
      },
      {
        name: "PlaneTracker", file: "web/arail/core/tracker.js", kind: "class", role: "Survey, pose, smoothing and hold.",
        attributes: ["map: MarkerMap", "survey: boolean — measure unknown markers", "holdSeconds: number — 1.5 s without markers", "acc: Map — survey accumulators", "H: number[] | null — the smoothed homography layout → image", "state: object — {H, Hinv, visible, used, holding, rms, moving}"],
        operations: ["update(detections, time, camera, opts) — one frame", "liftMarkers(detections, camera, height) — tags lifted to their height", "resurvey(all)", "_survey(markers, still)", "_estimate(markers) — least squares, outliers dropped", "_learnFocal(est, camera)", "_smooth(est, still)", "_moving(moving)"],
      },
      {
        name: "Camera", file: "web/arail/core/camera.js", kind: "class", role: "Intrinsics: estimated, manual or calibrated focal length; lens distortion.",
        attributes: ["width: number", "height: number", "calibration: object | null — from arail-calibrate", "manualFocal: number | null", "autoFocal: number | null — median of the estimates"],
        operations: ["setSize(width, height)", "addFocalSample(f)", "undistortPoints(points)", "project(X)", "setManualFocal(f)", "setCalibration(json)"],
      },
      {
        name: "geometry", file: "web/arail/core/geometry.js", kind: "module", role: "Marker geometry without calibration.",
        operations: ["markerHomography(imageCorners, size)", "relativeMarkerPose(Ha, Hb) — distance = pixel distance / √(sₐ·s_b)", "focalFromHomography(H, cx, cy)", "poseFromHomography(H, K)", "cameraCentre(pose)", "planeHomography(H, K, height)"],
      },
      {
        name: "VideoSurvey", file: "web/app/survey.js", kind: "class", role: "Build → Marker map → Survey a video: every 2nd frame of a video through a tracker of its own.",
        operations: ["cancel()"],
      },
    ],
    relations: [
      { from: "World", to: "MarkerMap", kind: "composes", label: "map" },
      { from: "PlaneTracker", to: "MarkerMap", kind: "aggregates", label: "map" },
      { from: "PlaneTracker", to: "Camera", kind: "uses" },
      { from: "PlaneTracker", to: "geometry", kind: "depends" },
      { from: "App", to: "PlaneTracker", kind: "creates", label: "per layout" },
      { from: "VideoSurvey", to: "PlaneTracker", kind: "creates" },
    ],
    activities: [
      {
        id: "frame", name: "One frame of the app",
        description: "App.frame, once per animation frame: markers found and tracked (camera image, photo or video), the world advanced and drawn.",
        nodes: [
          ["s", "start"],
          ["a1", "action", "Advance the app's clock", "App.frame"],
          ["d1", "decision", "Camera image (not the flyover), not frozen?"],
          ["a2", "action", "Draw the frame at the processing size; detect the markers", "App._processVideo"],
          ["a3", "action", "Update the tracker: survey, pose", "PlaneTracker.update"],
          ["a4", "action", "Tags lifted to their height for the terminal", "App._observeRolling"],
          ["m1", "merge"],
          ["a5", "action", "The control system's feed (simulated) and the world step", "World.step"],
          ["d2", "decision", "Flyover?"],
          ["a6", "action", "The virtual camera moves and draws", "Flyover.step"],
          ["a7", "action", "The pose to a View; the world drawn over the image", "App.render"],
          ["m2", "merge"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "m1", "no"], ["a2", "a3"], ["a3", "a4"], ["a4", "m1"], ["m1", "a5"], ["a5", "d2"], ["d2", "a6", "yes"], ["d2", "a7", "no"], ["a6", "m2"], ["a7", "m2"], ["m2", "e"]],
      },
      {
        id: "update", name: "PlaneTracker.update",
        nodes: [
          ["s", "start"],
          ["d1", "decision", "The map configured anew?"],
          ["a1", "action", "Forget the survey and the pose", "PlaneTracker.reset"],
          ["m1", "merge"],
          ["a2", "action", "Undistort the corners; moving markers aside; one homography per marker", "markerHomography"],
          ["d2", "decision", "Surveying and the map not locked?"],
          ["a3", "action", "Unknown markers measured from known ones, averaged over frames", "PlaneTracker._survey"],
          ["m2", "merge"],
          ["a4", "action", "One homography from all known markers; worst outliers dropped", "PlaneTracker._estimate"],
          ["d3", "decision", "A pose?"],
          ["a5", "action", "Learn the focal length; smooth the homography", "PlaneTracker._smooth"],
          ["d4", "decision", "No marker for 1.5 s?"],
          ["a6", "action", "Lose the pose"],
          ["m3", "merge"],
          ["a7", "action", "The state: pose, markers seen and used, moving markers", "PlaneTracker._moving"],
          ["e", "end"],
        ],
        edges: [["s", "d1"], ["d1", "a1", "yes"], ["d1", "m1", "no"], ["a1", "m1"], ["m1", "a2"], ["a2", "d2"], ["d2", "a3", "yes"], ["d2", "m2", "no"], ["a3", "m2"], ["m2", "a4"], ["a4", "d3"], ["d3", "a5", "yes"], ["d3", "d4", "no"], ["d4", "a6", "yes"], ["d4", "m3", "no: hold the last pose"], ["a5", "m3"], ["a6", "m3"], ["m3", "a7"], ["a7", "e"]],
      },
    ],
    parameters: [
      { key: "markers.size_mm", default: "30", meaning: "Edge of the markers (sizes_mm per marker)." },
      { key: "markers.origin", default: "the lowest ID seen", meaning: "The marker at the layout's origin." },
      { key: "markers.locked", default: "false", meaning: "Keep positions: a complete map, nothing is surveyed." },
      { key: "markers.moving", default: "[]", meaning: "Markers on vehicles: reported, never surveyed nor used for the pose." },
    ],
    rules: [
      "The first marker seen (the lowest ID of the first frame), or the configured origin, defines the layout frame.",
      "Survey weight 1/(d² + (5·size)²); pairs closer than 1.2 marker sizes are skipped; three frames before a marker is used in video, one in a photo.",
      "Pose: normalised least squares over all corners; while more than two markers: drop the worst if its error exceeds max(3 px, 0.2 × its edge).",
      "Smoothing: α = min(1, 0.25 + shift/12 px), off when the camera stands still; the pose is held 1.5 s without markers.",
      "3D pose from the homography: the plane lies in front of the camera where most of a 3×3 grid of image points sees it; the layout origin may lie behind the camera (a long layout, filmed far from it).",
      "Focal length: ≥ 3 markers spread over ≥ 40 mm, plane tilted 15–80°, 0.25·W < f < 5·W; median of the latest 600 estimates.",
      "While surveying, a marker seen in more than 10 frames is written into the map every 8 frames, or at once when it moved by more than 0.25 mm or 0.03°.",
    ],
  },
  {
    id: "flycam", group: "tracking", title: "The flyover's camera",
    summary: "A virtual orbit camera that gives the same homography and pose as a real one, so everything draws without video.",
    description: "FlyCamera describes its image like a real camera's: H = K [r₁ r₂ t] for a pinhole camera of focal length f, so the View, the editor and the simulations work unchanged. The app's Flyover drives it (orbit, pan, zoom, twist, fit, following a traveller) and draws the table, the orthophoto, the grid and the markers under the world.",
    files: ["web/arail/core/flycam.js", "web/app/flyover.js"],
    classes: [
      {
        name: "FlyCamera", file: "web/arail/core/flycam.js", kind: "class", role: "Orbit camera: state, projection, navigation.",
        attributes: ["target: number[] — the point looked at (mm)", "distance: number — mm", "yaw: number — rad", "pitch: number — rad, 8° … 90° (plan view)", "fovY: number — rad"],
        operations: ["set(view) — target, distance, yaw, pitch, fovY", "homography(width, height) — {H, Hinv, focal, pose}", "groundPoint(u, v, width, height, maxRange)", "orbit(dYaw, dPitch)", "pan(dx, dy, width, height, at)", "zoomAt(factor, px, py, width, height)", "fit(bounds, aspect, margin)"],
      },
      {
        name: "Flyover", file: "web/app/flyover.js", kind: "class", role: "The app's flyover: input, background, orthophoto, grid, markers, following.",
        attributes: ["cam: FlyCamera", "camera: Camera — with the virtual focal length", "active: boolean", "following: object | null — what the camera follows"],
        operations: ["enter()", "leave()", "pose() — the virtual camera's pose", "step(dt)", "render()", "follow(where)"],
      },
    ],
    relations: [
      { from: "Flyover", to: "FlyCamera", kind: "composes", label: "cam" },
      { from: "Flyover", to: "Camera", kind: "composes", label: "camera" },
      { from: "App", to: "Flyover", kind: "composes", label: "flyover" },
    ],
    activities: [{
      id: "frame", name: "One frame of the flyover",
      nodes: [
        ["s", "start"],
        ["d1", "decision", "An animation (fly to, fit)?"],
        ["a1", "action", "Interpolate the camera", "FlyCamera.set"],
        ["m1", "merge"],
        ["d2", "decision", "Following something?"],
        ["a2", "action", "Ease the target towards it", "Flyover.step"],
        ["m2", "merge"],
        ["a3", "action", "Homography and pose of the virtual camera", "Flyover.pose"],
        ["a4", "action", "Floor, tables, orthophoto, grid, markers; then the world", "Flyover.render"],
        ["e", "end"],
      ],
      edges: [["s", "d1"], ["d1", "a1", "yes"], ["d1", "m1", "no"], ["a1", "m1"], ["m1", "d2"], ["d2", "a2", "yes"], ["d2", "m2", "no"], ["a2", "m2"], ["m2", "a3"], ["a3", "a4"], ["a4", "e"]],
    }],
    rules: ["focal length f = h / 2 / tan(fovY / 2)", "Panning at most 4 × the distance away; the distance 25 mm … 60 m."],
  },
];
