/**
 * Models of the architecture page: stops, the timetable's vehicles, passengers, the town, streets,
 * bus lines and cars. See ../model.js for the format.
 * @module architecture/models/transport
 */
export const TRANSPORT = [
  {
    id: "stops", group: "transport", title: "Stop areas and docks",
    summary: "Where people wait and vehicles stop: platforms, bus stops and bus terminals give stop areas (in prototype metres) with docks along their edges; every simulation uses this interface.",
    description: "A stop area is a rectangle with s along it (0 … L) and t across it (+ is left); its docks are the places along an edge where a train or bus stands (a platform's two tracks, a bus stop's side of the street, a terminal's bays), its access points are where people come and go. Docks of bus lines are managed by the bus lines (managed: \"line\"), the others by the timetable.",
    files: ["web/arail/core/stops.js", "web/arail/objects/platform.js", "web/arail/objects/bus-stop.js", "web/arail/objects/bus-terminal.js"],
    classes: [
      {
        name: "StopArea", file: "web/arail/core/stops.js", kind: "class", role: "A waiting area: s along, t across, in prototype metres.",
        attributes: ["id: string — the owner's id (a bus stop: id:right, id:left)", "owner: LayoutObject", "kind: string — rail or bus", "L: number — length (m)", "W: number — width (m)", "docks: object[] — {id, side, s0, s1, kind, track, headway, dwell, managed}", "access: object[] — where people come and go"],
        operations: ["toLayout(s, t) — m to layout mm", "fromLayout(p) — layout mm to [s, t]", "outline()"],
      },
      { name: "BusTerminal", file: "web/arail/objects/bus-terminal.js", kind: "class", extends: "LayoutObject", role: "Bays; those of bus lines are managed by them.", operations: ["stopAreas()", "busLane() — the lane of the road network"] },
    ],
    relations: [
      { from: "Platform", to: "StopArea", kind: "creates", label: "1" },
      { from: "BusStop", to: "StopArea", kind: "creates", label: "1–2" },
      { from: "BusTerminal", to: "StopArea", kind: "creates", label: "1" },
    ],
    parameters: [{ key: "services", default: "rail_headway_s 70, rail_dwell_s 24, bus_headway_s 90, bus_dwell_s 20, approach_s 6", meaning: "Headway and dwell of the docks (simulated s); a platform can set its own." }],
    rules: ["Access points by default at 0.3 m and L − 0.3 m (weight 0.35 each) and L/2 (0.3).", "1 m of the prototype = 1000 / scale mm."],
  },
  {
    id: "services", group: "transport", title: "The timetable's trains and buses at the docks",
    summary: "Each dock not run by a bus line has a small state machine: its vehicles come by the headway, arrive, dwell and leave; the control system's trains (mode feed) or a planner's trains (mode plan) can take over a dock.",
    files: ["web/arail/core/services.js", "web/arail/core/vehicles.js"],
    classes: [
      {
        name: "ServiceManager", file: "web/arail/core/services.js", kind: "class", role: "world.services: the docks and their vehicles.",
        attributes: ["docks: Map — dock id → {dock, vehicle, timer, heldFor, mode}", "planner: object | null — rail operations or journeys: claims(dock), statusLines(area)"],
        operations: ["sync() — docks in line with the stop areas", "baseMode(dock) — plan if the planner claims it", "step(dt)", "call(target, options) — send a vehicle (keys 1–9, scenarios, planners)", "feedArrived(dockId, info)", "feedDeparted(dockId)", "_dispatch(st, opts)", "_advance(st, v, dt, fx)", "placement(v)", "doors(v)", "draw(view)"],
      },
      {
        name: "Vehicle", file: "web/arail/core/services.js", kind: "class", role: "A train or bus at one dock.",
        attributes: ["kind: string — train or bus", "line: string", "source: string — timetable, manual, scenario, plan, feed", "phase: string — arriving, dwelling, departing", "dwellLeft: number — s", "delayMin: number"],
        operations: ["doorsOpen — getter"],
      },
      { name: "vehicles", file: "web/arail/core/vehicles.js", kind: "module", role: "How trains and buses look: TRAIN and BUS (registered vehicles).", attributes: ["TRAIN — a multiple unit, doors every 7 m", "BUS — a 12 m bus, two doors"] },
    ],
    relations: [
      { from: "ServiceManager", to: "Vehicle", kind: "composes", label: "0..1 per dock" },
      { from: "ServiceManager", to: "DisruptionManager", kind: "uses", label: "effectsFor" },
      { from: "ServiceManager", to: "vehicles", kind: "depends", label: "doors, drawing" },
    ],
    activities: [{
      id: "dock", name: "A vehicle at a dock",
      nodes: [
        ["s", "start"],
        ["d0", "decision", "Mode of the dock?"],
        ["m0", "merge"],
        ["a1", "action", "Count down: headway × demand × frequency", "ServiceManager.step"],
        ["d1", "decision", "Due?"],
        ["a2", "action", "Cancelled: the next headway", "ServiceManager.step"],
        ["x1", "send", "vehicle.cancelled"],
        ["a3", "action", "Held: the dock busy, closed or held", "ServiceManager.step"],
        ["m1", "merge"],
        ["a4", "action", "A new vehicle comes in", "ServiceManager._dispatch"],
        ["x2", "send", "vehicle.arriving"],
        ["a5", "action", "After the approach it stands: doors open", "ServiceManager._advance"],
        ["x3", "send", "vehicle.arrived"],
        ["m2", "merge"],
        ["d2", "decision", "Dwell over, closed, or the train moves on?"],
        ["a6", "action", "Doors close, it leaves; the dock is free", "ServiceManager._advance"],
        ["x4", "send", "vehicle.departed"],
        ["e", "end"],
      ],
      edges: [["s", "d0"], ["d0", "m0", "timetable"], ["d0", "m1", "plan: the planner calls"], ["d0", "m2", "feed: a real train stands there"], ["m0", "a1"], ["a1", "d1"], ["d1", "m0", "no"], ["d1", "a2", "cancelled"], ["d1", "a3", "held"], ["d1", "m1", "free"], ["a2", "x1"], ["x1", "m0"], ["a3", "m0"], ["m1", "a4"], ["a4", "x2"], ["x2", "a5"], ["a5", "x3"], ["x3", "m2"], ["m2", "d2"], ["d2", "m2", "no"], ["d2", "a6", "yes"], ["a6", "x4"], ["x4", "e"]],
    }],
    events: {
      emits: [
        { name: "vehicle.arriving", payload: "vehicle, dock, area", when: "dispatched" },
        { name: "vehicle.arrived", payload: "vehicle, dock, area", when: "standing, doors open" },
        { name: "vehicle.departing", payload: "vehicle, dock, area", when: "dwell over" },
        { name: "vehicle.departed", payload: "vehicle, dock, area", when: "gone" },
        { name: "vehicle.cancelled", payload: "vehicle, dock, area", when: "a cancelled service was due" },
      ],
    },
    rules: [
      "The first vehicle after 0.15–0.6 × the headway, then every 0.7–1.3 × the headway (× the demand of the hour).",
      "A planner's vehicle stays until the planner lets it go (dwellLeft = ∞, then 0).",
      "Mode feed while the control system sends trains; closed ends a dwell (not a real train's), hold does not.",
    ],
  },
  {
    id: "passengers", group: "transport", title: "Passengers at the stops",
    summary: "A social-force crowd model per stop area: people arrive, find a waiting spot, wait (their mood falling with crowding and waiting), board through the doors, alight and leave; other simulations hand their people over.",
    description: "Every person is attracted to a target (a waiting spot, a door, an exit) and pushed away by neighbours closer than 0.6 m; local density slows walkers and worsens their mood. New people come with the demand of the hour, the global demand, disruptions and a slow wave; alighting passengers come with every arriving vehicle. Other simulations (the town, the journeys) hand their people over with enter() and alight(): they wait for their own line or train and are reported back with passenger.boarded and passenger.exited.",
    files: ["web/arail/sims/passengers.js"],
    classes: [
      {
        name: "PassengerSimulation", file: "web/arail/sims/passengers.js", kind: "class", extends: "Simulation", role: "The crowds of all stop areas.",
        attributes: ["crowds: Map — Crowd per stop area", "others: boolean — generated passengers (off: only those handed over)"],
        operations: ["step(dt)", "enter(areaId, opts) — a person of another simulation waits for its line", "alight(vehicle, dock, agents)", "release(person)", "_stepCrowd(c, dt) — arrivals, giving up", "_move(c, dt, fx) — forces, states, mood", "_board(p, dock, doors, delay, vehicle)", "_arrived(e)", "_departing(e)", "_cancelled(e)", "_wants(p, dock, vehicle)"],
      },
      { name: "Crowd", file: "web/arail/sims/passengers.js", kind: "class", role: "The people of one stop area.", attributes: ["area: StopArea", "people: Person[]"], operations: ["wave() — demand 0.3 … 1 over 180 s"] },
      {
        name: "Person", file: "web/arail/sims/passengers.js", kind: "class", role: "A pedestrian at a stop (s, t in m); not the Person of core/people.js.",
        attributes: ["pos: number[]", "vel: number[] — m/s", "target: number[]", "state: string — arriving, waiting, boarding, onboard, leaving", "mood: number — 0 … 1", "speed: number — 1.0–1.5 m/s", "agent: object | null — the person of another simulation"],
      },
      { name: "passengers", file: "web/arail/sims/passengers.js", kind: "module", role: "Forces and boards.", operations: ["crowdForces(people)", "statusLines(world, area) — the board over a stop", "boardStatus(world, areas, max)", "drawPerson(view, at, o)"] },
    ],
    relations: [
      { from: "PassengerSimulation", to: "Crowd", kind: "composes", label: "1 per stop area" },
      { from: "Crowd", to: "Person", kind: "composes", label: "people *" },
      { from: "Crowd", to: "StopArea", kind: "uses", label: "area" },
      { from: "PassengerSimulation", to: "ServiceManager", kind: "uses", label: "doors" },
      { from: "PassengerSimulation", to: "passengers", kind: "depends", label: "crowdForces" },
    ],
    activities: [
      {
        id: "board", name: "A passenger arrives, waits and boards",
        nodes: [
          ["s", "start"],
          ["a1", "action", "Appear at an access point (or handed over: enter); a waiting spot", "PassengerSimulation._stepCrowd"],
          ["m1", "merge"],
          ["a2", "action", "Walk to it: attraction, repulsion, slowed by density", "PassengerSimulation._move"],
          ["d1", "decision", "Within 0.4 m?"],
          ["m2", "merge"],
          ["a3", "action", "Wait: shift the feet; the mood falls", "PassengerSimulation._move"],
          ["r1", "receive", "vehicle.arrived"],
          ["d2", "decision", "A vehicle it wants (its line, its train)?"],
          ["d3", "decision", "Give up (closed, no service)?"],
          ["a4", "action", "Board: to the nearest door after a short delay; mood up", "PassengerSimulation._board"],
          ["d4", "decision", "The vehicle leaves first?"],
          ["a5", "action", "Missed it: wait again, mood down", "PassengerSimulation._departing"],
          ["a6", "action", "Through the door", "PassengerSimulation._move"],
          ["x1", "send", "passenger.boarded"],
          ["a7", "action", "Walk to an exit and leave", "PassengerSimulation._stepCrowd"],
          ["x2", "send", "passenger.exited"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "m1"], ["m1", "a2"], ["a2", "d1"], ["d1", "m1", "no"], ["d1", "m2", "yes"], ["m2", "a3"], ["a3", "r1"], ["r1", "d2"], ["d2", "a4", "yes"], ["d2", "d3", "no"], ["d3", "a7", "yes"], ["d3", "m2", "no"], ["a4", "d4"], ["d4", "a5", "yes"], ["d4", "a6", "no"], ["a5", "m2"], ["a6", "x1"], ["x1", "e"], ["a7", "x2"], ["x2", "e"]],
      },
      {
        id: "alight", name: "Alighting and leaving",
        nodes: [
          ["s", "start"],
          ["r1", "receive", "vehicle.arrived"],
          ["a1", "action", "Appear at the doors (handed over: alight), each after a short delay", "PassengerSimulation._arrived"],
          ["m1", "merge"],
          ["d1", "decision", "Delay over?"],
          ["a2", "action", "Walk to an exit (the one its next walk starts from)", "PassengerSimulation._move"],
          ["x1", "send", "passenger.exited"],
          ["e", "end"],
        ],
        edges: [["s", "r1"], ["r1", "a1"], ["a1", "m1"], ["m1", "d1"], ["d1", "m1", "no"], ["d1", "a2", "yes"], ["a2", "x1"], ["x1", "e"]],
      },
    ],
    parameters: [
      { key: "base_rate", default: "0.5", meaning: "Arrivals (people/s per 25 m of stop).", sim: "passengers" },
      { key: "max_per_area", default: "140", meaning: "Most people generated at a stop (handed-over people are not limited).", sim: "passengers" },
      { key: "others", default: "true", meaning: "Generated passengers; the module Journeys switches them off.", sim: "passengers" },
    ],
    events: {
      emits: [
        { name: "passenger.boarded", payload: "area, dock, vehicle, person, agent", when: "through the door" },
        { name: "passenger.exited", payload: "area, person, agent, pos", when: "left the stop" },
        { name: "passenger.removed", payload: "agent, person", when: "taken off (the stop removed, cleared)" },
      ],
      listens: [
        { name: "vehicle.arrived", does: "alighting and boarding" },
        { name: "vehicle.departing", does: "those on the way to the doors missed it" },
        { name: "vehicle.cancelled", does: "the mood of those waiting drops" },
      ],
    },
    rules: [
      "Neighbours within 1.3 m; closer than 0.6 m they push apart with 1.4 (0.6 − d)/0.6 m/s; density = max(0, neighbours − 2).",
      "Walking: v = unit(target − pos) × speed × min(1, dist/0.8) / (1 + 0.12 × density) + push; standing: 0.6 (target − pos) + 0.7 push; velocity eased (4/s).",
      "Mood per s while waiting: −(0.002 + 0.005 × density + 0.006 after 60 s) plus the disruptions' mood; boarding +0.02; leaving +0.008 − 0.004 × density.",
      "Arrivals: Poisson(base_rate × demand × disruption demand × wave × L/25 × the hour's demand × dt); none while closed, out of service, or without others.",
      "A standing vehicle is boarded while it has more than 6 s to go (a real train always).",
    ],
  },
  {
    id: "town", group: "transport", title: "The town's residents",
    summary: "Residents of the residential buildings with daily plans (work, school, shopping, home, the train): they walk the sidewalks, take buses and trains, and fill the buildings, whose windows light up.",
    files: ["web/arail/sims/town.js", "web/arail/objects/station.js"],
    classes: [
      {
        name: "TownSimulation", file: "web/arail/sims/town.js", kind: "class", extends: "Simulation", role: "The town.",
        attributes: ["agents: Agent[]", "places: object — buildings by use"],
        operations: ["step(dt)", "_build()", "_makePlan(a, day)", "_placeAll() — after clock.set", "_startTrip(a, step)", "_legsTo(a, from, fromKey, destId)", "_bestBus(from, dest, fromKey, destKey, walkM)", "_beginLeg(a)", "_walk(a, dt)", "townStats()"],
      },
      {
        name: "Agent", file: "web/arail/sims/town.js", kind: "class", extends: "Person", role: "A resident or visitor.",
        attributes: ["plan: object[] — {at, purpose, to, byTrain}", "state: string — inside, walking, stop, riding, away", "inside: string | null — the building", "purpose: string", "trip: object — its legs"],
      },
      { name: "StationBuilding", file: "web/arail/objects/station.js", kind: "class", extends: "BuildingBase", role: "The station building: a shop and a workplace." },
    ],
    relations: [
      { from: "TownSimulation", to: "Agent", kind: "composes", label: "agents *" },
      { from: "TownSimulation", to: "PassengerSimulation", kind: "uses", label: "enter, alight, release" },
      { from: "TownSimulation", to: "Transit", kind: "uses", label: "connections" },
      { from: "TownSimulation", to: "RoadNetwork", kind: "uses", label: "routes" },
    ],
    activities: [{
      id: "day", name: "A resident's day",
      nodes: [
        ["s", "start"],
        ["m0", "merge"],
        ["a1", "action", "Today's plan", "TownSimulation._ensurePlan"],
        ["d1", "decision", "A step of the plan due?"],
        ["a2", "action", "Leave the building; the legs: walk, bus or train", "TownSimulation._startTrip"],
        ["a3", "action", "Commuters get off an arriving train", "TownSimulation._trainArrivals"],
        ["m1", "merge"],
        ["a4", "action", "The next leg", "TownSimulation._beginLeg"],
        ["d2", "decision", "Which leg?"],
        ["a5", "action", "Walk on the sidewalk", "TownSimulation._walk"],
        ["a6", "action", "Wait at the stop (handed to the passengers)", "TownSimulation._beginLeg"],
        ["d3", "decision", "What happened at the stop?"],
        ["a7", "action", "Waited 20 min: walk instead, or home", "TownSimulation._exited"],
        ["a8", "action", "Away by train", "TownSimulation._boarded"],
        ["a9", "action", "Ride the bus; off at its stop", "TownSimulation._vehicleArrived"],
        ["a10", "action", "Inside: the building's occupancy counts it", "TownSimulation._setInside"],
      ],
      edges: [["s", "m0"], ["m0", "a1"], ["a1", "d1"], ["d1", "m0", "no"], ["d1", "a2", "due"], ["d1", "a3", "a train home"], ["a2", "m1"], ["a3", "m1"], ["m1", "a4"], ["a4", "d2"], ["d2", "a5", "walk"], ["d2", "a6", "bus or train"], ["d2", "a10", "none left"], ["a5", "m1"], ["a6", "d3"], ["d3", "a7", "gave up"], ["d3", "a8", "boarded a train"], ["d3", "a9", "boarded a bus"], ["a7", "m1"], ["a8", "m0"], ["a9", "m1"], ["a10", "m0"]],
    }],
    parameters: [
      { key: "people_per_100", default: "12", meaning: "People shown per 100 residents.", sim: "town" },
      { key: "max_people", default: "300", meaning: "Most people shown.", sim: "town" },
      { key: "walk_max_m", default: "150", meaning: "Longest walk before the bus is considered (m).", sim: "town" },
      { key: "bus_share", default: "0.8", meaning: "Share of long ways taken by bus.", sim: "town" },
      { key: "commuters_out", default: "0.35", meaning: "Share of workers who work elsewhere (train).", sim: "town" },
      { key: "commuters_in", default: "40", meaning: "People per 100 local jobs who come by train.", sim: "town" },
      { key: "shopping", default: "0.5", meaning: "Share of adults who go shopping each day.", sim: "town" },
    ],
    events: {
      listens: [
        { name: "passenger.boarded", does: "riding, or away by train" },
        { name: "passenger.exited", does: "the next leg" },
        { name: "vehicle.arrived", does: "riders get off; commuters come home" },
        { name: "clock.set", does: "everybody placed anew" },
      ],
    },
    rules: [
      "Roles: 15 % pupils, 25 % seniors, the rest workers; commuters among the workers when there are platforms.",
      "Plans: work 06:30–08:00 until 15:30–17:30; school 07:00–07:40; shopping 08:30–11:30 and evenings; trains 05:45–07:45 and 16:00–18:30.",
      "The bus when a walk is longer than walk_max_m and the bus is faster (stops within 300 m); patience 20 clock minutes.",
      "Shops are open 07:00–21:00; at most 14 residents per train.",
    ],
  },
  {
    id: "network", group: "transport", title: "Streets and the road network",
    summary: "One graph of streets, footpaths, the underpass, bus lanes, building entrances and the access points of stops: routes on foot and by car, walks on the sidewalks that cross no track, driving lines.",
    files: ["web/arail/core/network.js", "web/arail/objects/road.js", "web/arail/objects/underpass.js"],
    classes: [
      {
        name: "RoadNetwork", file: "web/arail/core/network.js", kind: "class", role: "world.network(): rebuilt when objects, the marker map or the scale change.",
        attributes: ["nodes: object[] — junctions, places, ends", "edges: object[] — {road, length, kind, car, bus, walk, oneway, speed}", "places: Map — entrances and access points", "barriers: object[] — tracks people do not cross on their own"],
        operations: ["place(key)", "nearestNode(p, opts) — for walking, in a straight line over no track", "route(from, to, opts) — Dijkstra", "routeDirected(from, fromDir, to, toDir, opts)", "walk(from, to, keys) — on the sidewalks, or out of sight", "walkLine(path, from, to)", "crossesBarrier(a, b)", "pathAt(path, s)", "drivingLine(path, opts) — on the right lane", "junctions()", "boundaryNodes()"],
      },
      { name: "Underpass", file: "web/arail/objects/underpass.js", kind: "class", extends: "LayoutObject", role: "A footpath under the tracks." },
    ],
    relations: [
      { from: "RoadNetwork", to: "Road", kind: "uses", label: "roadInfo()" },
      { from: "RoadNetwork", to: "StopArea", kind: "uses", label: "access, docks" },
      { from: "RoadNetwork", to: "BusTerminal", kind: "uses", label: "busLane()" },
      { from: "RoadNetwork", to: "Track", kind: "uses", label: "walkBarrier()" },
    ],
    activities: [{
      id: "build", name: "Building the network",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Split the streets at their ends and corners; join ends, T and X junctions", "RoadNetwork._build"],
        ["a0", "action", "Barriers: the tracks", "RoadNetwork._build"],
        ["a2", "action", "Places: entrances and stop access points within 80 m, not across a track; bus lanes", "RoadNetwork._build"],
        ["a3", "action", "Nodes, street edges, connectors", "RoadNetwork._build"],
        ["a4", "action", "One-way lanes past the bus bays", "RoadNetwork._addLane"],
        ["e", "end"],
      ],
      edges: [["s", "a0"], ["a0", "a1"], ["a1", "a2"], ["a2", "a3"], ["a3", "a4"], ["a4", "e"]],
    }, {
      id: "walk", name: "A walk",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Start and goal: their places, else the nearest nodes reached in a straight line over no track", "RoadNetwork.walk"],
        ["d1", "decision", "A route on foot?"],
        ["a2", "action", "Each street on the sidewalk on the side the walk comes from, kept round corners", "RoadNetwork.walkLine"],
        ["a3", "action", "Across at right angles at the end of a street where the next place lies on the other side", "RoadNetwork.walkLine"],
        ["a4", "action", "Footpaths and connectors join the sidewalk; the underpass out of sight", "RoadNetwork.walkLine"],
        ["d2", "decision", "Any streets at all?"],
        ["a5", "action", "Out of sight (round the back of the layout)", "straightWalk"],
        ["a6", "action", "Straight; out of sight if it would cross a track", "straightWalk"],
        ["m", "merge"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["a2", "a3"], ["a3", "a4"], ["a4", "m"], ["d1", "d2", "no"], ["d2", "a5", "yes"], ["d2", "a6", "no"], ["a5", "m"], ["a6", "m"], ["m", "e"]],
    }],
    rules: [
      "Streets 50 km/h (residential 30), footpaths for walking only (1.3 m/s).",
      "People do not cross tracks on their own: only on streets and footpaths over them (crossings, the underpass).",
      "Costs: walking by length, vehicles by time; trees of shortest paths cached (400).",
      "A U-turn costs 30 s at a dead end, else 600 s; lanes at a quarter of the street's width, sidewalks beside it.",
    ],
  },
  {
    id: "transit", group: "transport", title: "Bus lines",
    summary: "A bus line is a circuit through its stops on the road network; buses are dispatched at its ends by the headway and the hour's demand, drive on the right lane, keep their distance, give way at junctions, stop, dwell and lay over, carrying riders.",
    files: ["web/arail/core/transit.js", "web/arail/objects/bus-line.js"],
    classes: [
      {
        name: "Transit", file: "web/arail/core/transit.js", kind: "class", role: "world.transit: the bus lines and their buses.",
        attributes: ["lines: Map — circuit, visits, headway, speed, problems", "buses: LineBus[]"],
        operations: ["sync()", "step(dt)", "_dispatch(line, dt)", "_spawn(line, st)", "_drive(bus, line, dt, users)", "_arrive(bus, line, v)", "_drop(bus) — to the depot", "connections(fromAreaId, toAreaId) — for the town and the journeys", "vehicleAt(dockId)", "statusFor(dockId)"],
      },
      {
        name: "LineBus", file: "web/arail/core/transit.js", kind: "class", role: "A bus of a line (looks like a Vehicle to the passengers).",
        attributes: ["lineId: string", "riders: object[] — {agent, toDockId}", "phase: string — driving, arriving, dwelling, departing, gone", "s: number — mm along the circuit", "v: number — m/s"],
        operations: ["doorsOpen — getter"],
      },
      { name: "BusLine", file: "web/arail/objects/bus-line.js", kind: "class", extends: "LayoutObject", role: "A bus line placed through its stops (Build).", operations: ["lineLabel()", "problems()"] },
      { name: "transit", file: "web/arail/core/transit.js", kind: "module", role: "Rules shared with the cars.", operations: ["gapAhead(self, front, dir, users, lookMM, laneMM)", "mustYield(self, j, d, users)", "linesServing(world, objectId)"] },
    ],
    relations: [
      { from: "Transit", to: "LineBus", kind: "composes", label: "buses *" },
      { from: "Transit", to: "BusLine", kind: "uses", label: "spec" },
      { from: "Transit", to: "RoadNetwork", kind: "uses", label: "routes, driving lines" },
      { from: "Transit", to: "transit", kind: "depends" },
    ],
    activities: [{
      id: "round", name: "A line bus's round",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Dispatched: no bus waiting at the start; it appears before it", "Transit._spawn"],
        ["m1", "merge"],
        ["a2", "action", "Drive: speed, gap, give way at junctions; closed stops passed", "Transit._drive"],
        ["x1", "send", "vehicle.arriving"],
        ["d1", "decision", "At its stop?"],
        ["a3", "action", "Stop, doors open; riders get off, people get on", "Transit._arrive"],
        ["x2", "send", "vehicle.arrived"],
        ["d2", "decision", "Its end, and not due?"],
        ["a4", "action", "Lay over until it is dispatched", "Transit._dispatch"],
        ["m2", "merge"],
        ["d3", "decision", "Dwell over?"],
        ["d4", "decision", "Out of service (too many buses, cancelled, waited too long)?"],
        ["a5", "action", "To the depot", "Transit._drop"],
        ["a6", "action", "Doors close; to the next stop", "Transit._drive"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "m1"], ["m1", "a2"], ["a2", "x1"], ["x1", "d1"], ["d1", "m1", "no"], ["d1", "a3", "yes"], ["a3", "x2"], ["x2", "d2"], ["d2", "a4", "yes"], ["d2", "m2", "no"], ["a4", "m2"], ["m2", "d3"], ["d3", "m2", "no"], ["d3", "d4", "yes"], ["d4", "a5", "yes"], ["d4", "a6", "no"], ["a5", "e"], ["a6", "m1"]],
    }],
    parameters: [
      { key: "headway_s", default: "240", meaning: "Headway of a bus line (BusLine)." },
      { key: "speed_kmh", default: "40", meaning: "Speed of its buses." },
      { key: "mode", default: "back-and-forth", meaning: "Back and forth, or a ring." },
    ],
    events: {
      emits: [
        { name: "vehicle.arriving", payload: "vehicle, dock, area", when: "60 m before a stop" },
        { name: "vehicle.arrived", payload: "vehicle, dock, area", when: "stopped" },
        { name: "vehicle.departing", payload: "vehicle, dock, area", when: "doors close" },
        { name: "vehicle.departed", payload: "vehicle, dock, area", when: "15 m on" },
        { name: "vehicle.cancelled", payload: "vehicle, dock, area", when: "a departure cancelled by a disruption" },
      ],
      listens: [{ name: "clock.set", does: "buses for lines that have none" }],
    },
    rules: [
      "Accelerate 1.0, brake 1.3 (hard 3.5) m/s²; gap 3 m; doors 2.5 s; dwell at least 8 s.",
      "Buses needed = ⌈cycle / (headway / demand)⌉ + 1; target speed = min(speed, limit, √(2 × 1.3 × d), √(2 × 1.3 × (gap − 3))).",
      "Give way at junctions for at most 4 s; lay over at most max(3 × headway, 600 s).",
    ],
  },
  {
    id: "traffic", group: "transport", title: "Road traffic",
    summary: "Cars enter at the ends of the streets, drive the fastest routes (sometimes a detour), keep their distance, give way at junctions and leave; their number follows cars per km and the hour.",
    files: ["web/arail/sims/traffic.js"],
    classes: [{
      name: "TrafficSimulation", file: "web/arail/sims/traffic.js", kind: "class", extends: "Simulation", role: "Cars on the road network.",
      attributes: ["cars: object[] — {path, dest, s, v, waited}"],
      operations: ["step(dt)", "targetCount(net)", "roadUsers() — positions for the buses", "_enter(net)", "_route(net, from, to)", "_car(net, route, dest, s0)", "_drive(car, dt, users, net)"],
    }],
    relations: [
      { from: "TrafficSimulation", to: "RoadNetwork", kind: "uses", label: "routes" },
      { from: "Transit", to: "TrafficSimulation", kind: "uses", label: "roadUsers()" },
    ],
    activities: [{
      id: "car", name: "A car in road traffic",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Fewer cars than the target: the spawn timer", "TrafficSimulation.step"],
        ["a2", "action", "An end of a street; a route", "TrafficSimulation._enter"],
        ["d1", "decision", "Entry clear?"],
        ["a3", "action", "Its driving line and junctions", "TrafficSimulation._car"],
        ["m1", "merge"],
        ["a4", "action", "Speed for the gap ahead; give way at junctions; move", "TrafficSimulation._drive"],
        ["d2", "decision", "End of its route?"],
        ["d3", "decision", "A dead end, or too many cars?"],
        ["a5", "action", "Leave", "TrafficSimulation._drive"],
        ["a6", "action", "A new route", "TrafficSimulation._route"],
        ["e", "end"],
        ["f", "flowfinal"],
      ],
      edges: [["s", "a1"], ["a1", "a2"], ["a2", "d1"], ["d1", "f", "no"], ["d1", "a3", "yes"], ["a3", "m1"], ["m1", "a4"], ["a4", "d2"], ["d2", "m1", "no"], ["d2", "d3", "yes"], ["d3", "a5", "yes"], ["d3", "a6", "no"], ["a5", "e"], ["a6", "m1"]],
    }],
    parameters: [{ key: "cars_per_km", default: "20", meaning: "Cars per km of street.", sim: "traffic" }],
    rules: ["Target = round(cars_per_km × km × the hour's demand for cars).", "Length 4.4 m; accelerate 2.0, brake 2.5 (hard 7) m/s²; gap 2.5 m.", "A detour with chance 0.3 if it is at most 1.5 × the direct way."],
  },
];
