/**
 * Models of the architecture page: the world (step loop, registry, events), layout files and layers,
 * the clock, objects, people and drawing. See ../model.js for the format.
 * @module architecture/models/world
 */
export const WORLD = [
  {
    id: "world", group: "world", title: "World, step and registry",
    summary: "The loaded layout: its objects, simulations and managers, advanced in sub-steps and drawn; types come from the registry, news goes over the event bus.",
    description: "World.load builds everything from a layout file: objects by their type from the registry, one simulation per entry of the layout's simulations, the services, bus lines, disruptions and scenarios. World.step advances simulated time in sub-steps of at most 0.25 s in a fixed order; the parts talk over the event bus and the effects of disruptions, so each can be replaced. index.js registers the built-in types (registerBuiltins), creates worlds (createWorld) and loads plugins, which get the whole API.",
    files: ["web/arail/core/world.js", "web/arail/core/simulation.js", "web/arail/core/registry.js", "web/arail/core/events.js", "web/arail/index.js", "web/arail/core/layers.js", "web/arail/core/layout.js"],
    classes: [
      {
        name: "World", file: "web/arail/core/world.js", kind: "class", role: "The loaded layout; step and draw.",
        attributes: ["registry: Registry", "events: EventBus", "clock: Clock", "objects: LayoutObject[]", "simulations: Simulation[]", "time: number — simulated s since loading", "speed: number — simulated s per real s", "paused: boolean", "demand: number — demand factor of the Settings", "objectsVersion: number — counts changes of objects"],
        operations: ["load(json) — compose the layers, defaults, everything anew", "toJSON() — the layout file, layers split again", "layers() — the layers (modules)", "addObject(spec)", "removeObject(id)", "objectChanged(obj)", "stopAreas() — cached", "network() — cached road network", "step(dtReal)", "setTime(value)", "draw(view, opts)", "pick(view, pixel, options) — what is at an image pixel", "card(hit) — its info card, with what the simulations and the card providers add", "findPickable(view, key) — the same thing now"],
      },
      {
        name: "Simulation", file: "web/arail/core/simulation.js", kind: "class", stereotype: "base class", role: "Base of all simulations: one per entry of the layout's simulations.",
        attributes: ["type: string — static, the key in the registry", "params: object[] — static, its settings", "world: World", "config: object — defaults and the entry", "enabled: boolean"],
        operations: ["step(dt)", "draw(view)", "stats(areaId)", "pickables(view) — its people and vehicles that can be pointed at", "card(hit) — the info card of one of them", "describeObject(object, card) — adds what it knows to an object's card", "describeAgent(agent) — the card of its person shown by another simulation", "describeVehicle(vehicle, card) — adds to the card of a vehicle at a stop", "clear()", "dispose()", "toJSON()"],
      },
      {
        name: "Registry", file: "web/arail/core/registry.js", kind: "class", role: "Extension points by type name.",
        attributes: ["objects: Map — object classes", "simulations: Map — simulation classes", "disruptions: Map — disruption definitions", "vehicles: Map — how vehicles are drawn", "cards: Map — card providers", "checks: Map — layout checks"],
        operations: ["registerObject(cls)", "registerSimulation(cls)", "registerDisruption(def)", "registerVehicle(def)", "registerCard(name, fn) — adds to info cards", "registerCheck(name, fn) — checks layout files"],
      },
      {
        name: "EventBus", file: "web/arail/core/events.js", kind: "class", role: "Publish and subscribe; \"*\" hears every event; errors of handlers are caught.",
        attributes: ["handlers: Map — name → handlers"],
        operations: ["on(name, handler) — returns an unsubscribe function", "once(name, handler)", "off(name, handler)", "emit(name, payload)"],
      },
      {
        name: "index", file: "web/arail/index.js", kind: "module", role: "The public API: the default registry, createWorld, plugins.",
        attributes: ["VERSION — the framework's version", "registry — registerBuiltins(new Registry())"],
        operations: ["registerBuiltins(registry) — core types, then terminal, operations, infrastructure, journeys", "createWorld(layout, opts)", "loadPlugins(urls, base, opts) — each plugin's default export gets the API"],
      },
    ],
    relations: [
      { from: "World", to: "EventBus", kind: "composes", label: "events" },
      { from: "World", to: "Clock", kind: "composes", label: "clock" },
      { from: "World", to: "LayoutObject", kind: "composes", label: "objects *" },
      { from: "World", to: "Simulation", kind: "composes", label: "simulations *" },
      { from: "World", to: "ServiceManager", kind: "composes", label: "services" },
      { from: "World", to: "Transit", kind: "composes", label: "transit" },
      { from: "World", to: "DisruptionManager", kind: "composes", label: "disruptions" },
      { from: "World", to: "ScenarioPlayer", kind: "composes", label: "scenarios" },
      { from: "World", to: "TrainRegistry", kind: "composes", label: "trains" },
      { from: "World", to: "Registry", kind: "aggregates", label: "registry" },
      { from: "World", to: "RoadNetwork", kind: "creates", label: "network()" },
      { from: "index", to: "World", kind: "creates", label: "createWorld" },
      { from: "index", to: "Registry", kind: "creates" },
    ],
    activities: [
      {
        id: "step", name: "World.step: one frame",
        description: "Called by the app every animation frame with the real time since the last one.",
        nodes: [
          ["s", "start"],
          ["a1", "action", "Keep the docks in line with the stop areas", "World._syncStops"],
          ["a2", "action", "The control system's trains (real time, also while paused)", "TrainRegistry.step"],
          ["d1", "decision", "Paused?"],
          ["a3", "action", "dt = real time (≤ 0.1 s) × speed, in sub-steps of ≤ 0.25 s", "World.step"],
          ["d2", "decision", "A sub-step left?"],
          ["a4", "action", "Advance the clock", "Clock.advance"],
          ["d3", "decision", "Past midnight?"],
          ["x1", "send", "clock.day"],
          ["m1", "merge"],
          ["a5", "action", "Scenario steps that are due", "ScenarioPlayer.step"],
          ["a6", "action", "Disruptions that expire", "DisruptionManager.step"],
          ["a7", "action", "Timetable trains and buses at the docks", "ServiceManager.step"],
          ["a8", "action", "Line buses: dispatch, drive, stop", "Transit.step"],
          ["a9", "action", "Object animations", "LayoutObject.update"],
          ["a10", "action", "The simulations, in the order of the layout (base, then the modules on)", "Simulation.step"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "a2"], ["a2", "d1"], ["d1", "e", "yes"], ["d1", "a3", "no"], ["a3", "d2"], ["d2", "a4", "yes"], ["d2", "e", "no"], ["a4", "d3"], ["d3", "x1", "yes"], ["d3", "m1", "no"], ["x1", "m1"], ["m1", "a5"], ["a5", "a6"], ["a6", "a7"], ["a7", "a8"], ["a8", "a9"], ["a9", "a10"], ["a10", "d2"]],
      },
      {
        id: "load", name: "Loading a layout",
        description: "The app's _applyLayout with World.load: plugins first (also those of modules that are off), then the layout.",
        nodes: [
          ["s", "start"],
          ["a1", "action", "The plugins of the layout and of all its layers", "layoutPlugins"],
          ["d1", "decision", "Plugins?"],
          ["a2", "action", "Import each; its default export registers its types", "loadPlugins"],
          ["m1", "merge"],
          ["a3", "action", "Check the layout with every layer on (only warned)", "validateLayout"],
          ["a4", "action", "Merge the layers that are on into the base", "composeLayout"],
          ["a5", "action", "Fill in the defaults", "normalizeLayout"],
          ["a6", "action", "Marker map and clock; services, disruptions, trains and bus lines reset", "World.load"],
          ["a7", "action", "Create the objects; dispose the old simulations", "World._create"],
          ["d2", "decision", "Another simulation entry?"],
          ["d3", "decision", "Its type registered?"],
          ["a8", "action", "Create it with its settings", "World.load"],
          ["a9", "action", "Keep the entry as it is (saved unchanged), warn", "World.load"],
          ["a10", "action", "Load the scenarios; the docks", "ScenarioPlayer.load"],
          ["x1", "send", "layout.loaded"],
          ["e", "end"],
        ],
        edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "m1", "no"], ["a2", "m1"], ["m1", "a3"], ["a3", "a4"], ["a4", "a5"], ["a5", "a6"], ["a6", "a7"], ["a7", "d2"], ["d2", "d3", "yes"], ["d3", "a8", "yes"], ["d3", "a9", "no"], ["a8", "d2"], ["a9", "d2"], ["d2", "a10", "no"], ["a10", "x1"], ["x1", "e"]],
      },
    ],
    parameters: [
      { key: "seed", default: "12345", meaning: "Random numbers of a world (createWorld); the simulations derive their streams from it." },
      { key: "speed", default: "2", meaning: "Simulated seconds per real second." },
      { key: "settings", default: "labels, trails, tracks, lighting, coverMarkers, trackSystems …", meaning: "What is drawn (View panel), kept in the browser; coverMarkers: grey plates with their numbers over the markers and the labels of model wagons (camera view, on by default); trackSystems: the railway system the tracks are coloured by (off by default)." },
    ],
    events: {
      emits: [
        { name: "layout.loaded", payload: "layout", when: "after loading" },
        { name: "object.added", payload: "object", when: "an object placed" },
        { name: "object.changed", payload: "object", when: "an object edited (also right before object.added)" },
        { name: "object.removed", payload: "object", when: "an object deleted" },
        { name: "clock.day", payload: "day", when: "midnight" },
        { name: "clock.set", payload: "minutes", when: "the time set by hand" },
      ],
    },
    rules: [
      "_syncStops and the control system's trains run also while the world is paused.",
      "A frame: real time capped at 0.1 s; sub-steps of at most 0.25 simulated seconds.",
      "Every simulation is stepped; each checks its own `enabled`.",
      "An unknown object type becomes an UnknownObject (saved as it was); an unknown simulation keeps its entry and is saved unchanged.",
      "Caches: the stop areas by marker map and scale; the road network also by objectsVersion.",
    ],
  },
  {
    id: "layout", group: "world", title: "Layout files and modules",
    summary: "Pure functions: layers (the app's modules) merged into a flat layout and split again, defaults filled in, problems found.",
    description: "A layout file has a base and layers. composeLayout merges the layers that are on into the base (an object with a known id patches it, a simulation entry with patch: true changes the base's simulation of that type); decomposeLayout puts edits back where they came from. A layer can be exclusive, or a layout of its own (the container terminal), which the app opens instead. Points can be given relative to a marker (anchors).",
    files: ["web/arail/core/layout.js", "web/arail/core/layers.js", "web/arail/core/anchors.js"],
    classes: [
      {
        name: "layout", file: "web/arail/core/layout.js", kind: "module", role: "Defaults and validation.",
        attributes: ["LAYOUT_FORMAT — \"arail-layout/1\"", "DEFAULT_SERVICES — headways and dwell times", "DEFAULT_GRID — 50 mm, snap", "DEFAULT_ROLLING — the tags of model wagons"],
        operations: ["normalizeLayout(json) — a copy with defaults", "validateLayout(json, registry) — problems, with every layer on", "isLayout(json)"],
      },
      {
        name: "layers", file: "web/arail/core/layers.js", kind: "module", role: "Switchable parts of one layout: the app's modules.",
        operations: ["composeLayout(json) — the layers that are on merged into the base", "decomposeLayout(flat, composed, opts) — edits back where they came from", "normalizeLayers(layers)", "withLayers(json, ids)", "toggleLayer(layers, on, id)", "layerChoice(layers, ids)", "layoutPlugins(json)", "layerProblems(json)"],
      },
      {
        name: "anchors", file: "web/arail/core/anchors.js", kind: "module", role: "Points as [x, y] or {marker, offset}, through the marker map.",
        operations: ["resolvePoint(map, p)", "resolvePoints(map, pts)", "translatePoint(map, p, dx, dy)", "markersUsed(spec)"],
      },
    ],
    relations: [
      { from: "World", to: "layers", kind: "depends", label: "load, toJSON" },
      { from: "World", to: "layout", kind: "depends", label: "load" },
      { from: "LayoutObject", to: "anchors", kind: "depends", label: "geometry" },
    ],
    activities: [{
      id: "module", name: "Switching a module",
      description: "View → Modules: App.toggleModule, then the layout is saved with its edits and loaded again with the new choice.",
      nodes: [
        ["s", "start"],
        ["d0", "decision", "A module of the app (Build, Disruptions)?"],
        ["a0", "action", "Switch it; its tab shows or hides (nothing is loaded again)", "App.setAppModule"],
        ["d1", "decision", "The module on?"],
        ["a1", "action", "Switch it off", "toggleLayer"],
        ["d2", "decision", "Exclusive?"],
        ["a2", "action", "It alone", "toggleLayer"],
        ["a3", "action", "Exclusive ones off; it on", "toggleLayer"],
        ["m1", "merge"],
        ["a4", "action", "In layer order; the first exclusive one alone", "layerChoice"],
        ["d3", "decision", "A layout of its own?"],
        ["a5", "action", "Open that layout; this one is its home", "App._openModuleLayout"],
        ["a6", "action", "The edited layout, split into base and layers", "decomposeLayout"],
        ["a7", "action", "The layers switched", "withLayers"],
        ["a8", "action", "Load it: the simulations start again", "World.load"],
        ["e", "end"],
      ],
      edges: [["s", "d0"], ["d0", "a0", "yes"], ["d0", "d1", "no"], ["a0", "e"], ["d1", "a1", "yes"], ["d1", "d2", "no"], ["d2", "a2", "yes"], ["d2", "a3", "no"], ["a1", "m1"], ["a2", "m1"], ["a3", "m1"], ["m1", "a4"], ["a4", "d3"], ["d3", "a5", "yes"], ["d3", "a6", "no"], ["a5", "e"], ["a6", "a7"], ["a7", "a8"], ["a8", "e"]],
    }],
    parameters: [
      { key: "scale", default: "87", meaning: "1 m of the prototype is 1000/87 mm (H0)." },
      { key: "services", default: "rail_headway_s 70, rail_dwell_s 24, bus_headway_s 90, bus_dwell_s 20, approach_s 6", meaning: "The built-in timetable (simulated seconds)." },
      { key: "grid", default: "size_mm 50, snap", meaning: "The grid of the flyover and Build." },
      { key: "layers[]", default: "enabled false, exclusive false, layout null", meaning: "The modules: objects, simulations, scenarios and plugins they add." },
    ],
    rules: [
      "World.load composes first, then fills in the defaults.",
      "The base is always on; the layers that are on apply in their order.",
      "A layer's object with an id that exists patches it (keys merged); a simulation entry with patch: true merges into the first simulation of its type.",
      "Decomposing: an object back to its layer; a key back to the last layer that patched it; a new object to the active layer (or the base).",
      "Validation and plugins include the layers that are off.",
    ],
  },
  {
    id: "clock", group: "world", title: "Fast clock, daylight and demand",
    summary: "Turns simulated seconds into a faster time of day, with daylight and the demand of trains, buses, cars and passengers over the day.",
    files: ["web/arail/core/clock.js"],
    classes: [
      {
        name: "Clock", file: "web/arail/core/clock.js", kind: "class", role: "The world's time of day.",
        attributes: ["minutes: number — time of day", "day: number", "factor: number — clock s per simulated s", "frozen: boolean", "profiles: boolean — demand over the day"],
        operations: ["configure(config)", "advance(dt) — true at midnight", "set(value)", "label()", "daylight()", "night()", "demand(kind)"],
      },
      {
        name: "clock", file: "web/arail/core/clock.js", kind: "module", role: "Times and profiles.",
        attributes: ["DAY_MINUTES — 1440", "SUN — rise 06:00, set 20:30, twilight 45 min", "PROFILES — rail, bus, car, passengers"],
        operations: ["parseTime(value)", "formatTime(minutes)", "profileAt(points, minutes)", "daylightAt(minutes, sun)"],
      },
    ],
    relations: [{ from: "Clock", to: "clock", kind: "depends" }],
    activities: [{
      id: "advance", name: "Clock.advance(dt)",
      nodes: [
        ["s", "start"],
        ["d1", "decision", "Stopped, or no time?"],
        ["a1", "action", "minutes += dt × factor / 60", "Clock.advance"],
        ["d2", "decision", "Past 24:00?"],
        ["a2", "action", "Next day; minutes wrapped (the world sends clock.day)", "Clock.advance"],
        ["e", "end"],
      ],
      edges: [["s", "d1"], ["d1", "e", "yes"], ["d1", "a1", "no"], ["a1", "d2"], ["d2", "a2", "yes"], ["d2", "e", "no"], ["a2", "e"]],
    }],
    parameters: [
      { key: "clock.start", default: "07:00", meaning: "Time of day when the layout is loaded." },
      { key: "clock.factor", default: "12", meaning: "Clock seconds per simulated second (1:12: an hour in five simulated minutes)." },
      { key: "clock.profiles", default: "true", meaning: "Demand over the day: rush hours, no trains and buses 01:00–04:30." },
    ],
    rules: ["night() = 1 − daylight(); twilight 45 min around sunrise and sunset.", "demand(kind) = 1 without profiles, else the profile of that kind at this minute.", "The layout file keeps the start time, not the current time."],
  },
  {
    id: "objects", group: "world", title: "Objects on the layout",
    summary: "Everything placed on a layout is a LayoutObject of a registered type: its spec, its geometry from the markers, its stop areas, its drawing.",
    description: "An object keeps its spec (as in the layout file) and caches its geometry until the marker map, the scale or the spec change. Platforms, bus terminals and bus stops give stop areas (where people wait and vehicles stop); streets give the road network; buildings (BuildingBase) give homes, workplaces and lit windows. The table of all types is under Extension points.",
    files: ["web/arail/core/object.js", "web/arail/objects/platform.js", "web/arail/objects/track.js", "web/arail/objects/station.js", "web/arail/objects/underpass.js", "web/arail/objects/road.js", "web/arail/objects/bus-stop.js", "web/arail/objects/bus-terminal.js", "web/arail/objects/bus-line.js", "web/arail/objects/signs.js", "web/arail/objects/building-kit.js", "web/arail/objects/building.js", "web/arail/objects/houses.js", "web/arail/objects/trees.js", "web/arail/objects/landscape.js", "web/arail/objects/label.js", "web/arail/objects/tabletop.js"],
    classes: [
      {
        name: "LayoutObject", file: "web/arail/core/object.js", kind: "class", stereotype: "base class", role: "Base of all objects.",
        attributes: ["type: string — static, the key in the registry", "params: object[] — static, the inspector's fields", "spec: object — as in the layout file", "id: string", "world: World"],
        operations: ["defaults() — static", "computeGeometry()", "set(patch)", "footprint()", "contains(p, toleranceMM)", "pickHeight() — pointed at up to this height (0: on the ground)", "card() — its info card", "translate(dx, dy)", "stopAreas()", "update(dt)", "draw(view)", "toJSON()"],
      },
      { name: "UnknownObject", file: "web/arail/core/object.js", kind: "class", extends: "LayoutObject", role: "A type nobody registered: kept as it is." },
      {
        name: "BuildingBase", file: "web/arail/objects/building-kit.js", kind: "class", extends: "LayoutObject", stereotype: "base class", role: "Base of the buildings: use, capacity, entrances, lit windows.",
        operations: ["capacity()", "entrances()", "occupancy()", "litShare(darkness)", "model()", "pickHeight() — its roof", "card() — use, floors, people it holds and inside now"],
      },
      {
        name: "BuildingModel", file: "web/arail/objects/building-kit.js", kind: "class", role: "A white model in prototype metres: boxes, windows, entrances; level of detail.",
        operations: ["box(x0, y0, x1, y1, z0, z1, opts)", "window(face, s0, s1, t0, t1, opts)", "entrance(x, y, nx, ny)", "finish(opts)"],
      },
      { name: "Platform", file: "web/arail/objects/platform.js", kind: "class", extends: "LayoutObject", role: "A platform with its tracks: rail docks on both edges.", operations: ["stopAreas()"] },
      { name: "Road", file: "web/arail/objects/road.js", kind: "class", extends: "LayoutObject", role: "A street or footpath of the road network.", operations: ["roadInfo()"] },
      { name: "Track", file: "web/arail/objects/track.js", kind: "class", extends: "LayoutObject", role: "The centre line of a real (or virtual) track: train positions by track and offset; people do not cross it on their own; a section with its railway systems.", operations: ["at(offsetMM)", "walkBarrier()", "card() — also its systems", "draw(view) — the track, a band by its system (View → Colour the tracks by)"] },
      { name: "BusStop", file: "web/arail/objects/bus-stop.js", kind: "class", extends: "LayoutObject", role: "A bus stop by the street: managed bus docks.", operations: ["stopAreas()"] },
      { name: "House", file: "web/arail/objects/houses.js", kind: "class", extends: "BuildingBase", role: "One of the house types (also Plattenbau, office, school …)." },
    ],
    relations: [{ from: "BuildingBase", to: "BuildingModel", kind: "creates", label: "model()" }],
    activities: [{
      id: "edit", name: "An object is edited",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Apply the patch to the spec", "LayoutObject.set"],
        ["a2", "action", "Count the change; docks in line with the stop areas", "World.objectChanged"],
        ["x1", "send", "object.changed"],
        ["d1", "decision", "Marker map, scale or spec changed since the last geometry?"],
        ["a3", "action", "Compute the geometry anew (null: cannot be placed)", "LayoutObject.computeGeometry"],
        ["m1", "merge"],
        ["a4", "action", "Draw it in the next frame", "LayoutObject.draw"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "a2"], ["a2", "x1"], ["x1", "d1"], ["d1", "a3", "yes"], ["d1", "m1", "no"], ["a3", "m1"], ["m1", "a4"], ["a4", "e"]],
    }],
    rules: ["The geometry is cached by marker map version, spec version and scale.", "toJSON writes the keys given explicitly or different from the defaults.", "Buildings light a share of their windows that follows their occupancy and the time of day; level of detail drops windows below 1.5 px."],
  },
  {
    id: "math", group: "world", title: "Maths",
    summary: "Small, exact helpers used everywhere: 2D and 3D vectors, poses, homographies (exact and least squares), polygons, polylines, angles and seeded random numbers.",
    files: ["web/arail/core/math.js"],
    classes: [{
      name: "math", file: "web/arail/core/math.js", kind: "module", role: "Pure functions, no state.",
      operations: ["solve(A, b) — a linear system", "homography4(src, dst) — exact from four points", "homographyLS(src, dst) — normalised least squares (DLT)", "applyH(H, p)", "poseApply(pose, p)", "polygonArea(poly)", "pointInPolygon(p, poly)", "polylineAt(pts, s)", "polylineProject(pts, p)", "createRng(seed) — seeded random numbers", "hashKey(...parts)"],
    }],
    rules: ["Random numbers are seeded (createRng): the same seed gives the same run; simulations take streams of their own (hash of the world's seed and their name)."],
  },
  {
    id: "people", group: "world", title: "People",
    summary: "The people of all simulations: names (birds, in the languages of people living in Germany), random streams per person, homes.",
    files: ["web/arail/core/people.js"],
    classes: [
      { name: "Person", file: "web/arail/core/people.js", kind: "class", role: "A person of any simulation.", attributes: ["id: string", "name: string — e.g. \"S. Fink\"", "given: string", "family: string", "lang: string", "role: string", "home: object — where the person lives"] },
      { name: "Population", file: "web/arail/core/people.js", kind: "class", role: "People of one scope with seed-stable unique names.", attributes: ["seed: number", "scope: string — town, journeys, person (crews), infra", "people: Map", "names: Set"], operations: ["rng(key, ...parts) — a random stream per person", "name(key)", "add(key, spec, Kind)"] },
      { name: "people", file: "web/arail/core/people.js", kind: "module", role: "Languages and homes.", attributes: ["LANGUAGES — 17, weighted"], operations: ["pickHome(rng, opts)", "residentialBuildings(world)"] },
    ],
    relations: [
      { from: "Population", to: "Person", kind: "composes", label: "people *" },
      { from: "Agent", to: "Person", kind: "inherits" },
      { from: "Traveller", to: "Person", kind: "inherits" },
    ],
    activities: [{
      id: "add", name: "Population.add: a new person",
      nodes: [
        ["s", "start"],
        ["a1", "action", "A language, by the hash of the key and the weights", "Population.name"],
        ["m1", "merge"],
        ["a2", "action", "Two different birds as given and family name", "Population.name"],
        ["d1", "decision", "Name free (or 50 tries)?"],
        ["a3", "action", "Create the person of its kind", "Population.add"],
        ["a4", "action", "Remember its id and name", "Population._take"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "m1"], ["m1", "a2"], ["a2", "d1"], ["d1", "m1", "no"], ["d1", "a3", "yes"], ["a3", "a4"], ["a4", "e"]],
    }],
    rules: ["pickHome: a station beyond the layout with the share outerShare, else a house weighted by its capacity, else away."],
  },
  {
    id: "rendering", group: "world", title: "Drawing",
    summary: "Each frame the world queues its drawing on a View (ground, solids, overlays), dimmed at night, and the View draws it sorted onto the canvas.",
    description: "The View projects layout points with the camera's homography and pose. Ground is drawn in order, solids far to near (painter's algorithm, back faces culled), overlays (labels) last and never darkened. At night every colour is darkened towards Dunkelblau, except emissive ones (windows, lamps, headlights). The simple view (Map, 2.5D) draws flat footprints and plain blocks.",
    files: ["web/arail/core/view.js", "web/arail/core/simple.js", "web/arail/core/colors.js"],
    classes: [
      {
        name: "View", file: "web/arail/core/view.js", kind: "class", role: "Projection and display list of one frame.",
        attributes: ["ctx: CanvasRenderingContext2D", "camera: Camera", "H: number[] — layout → image", "night: number | null — 0 day … 1 night", "virtual: boolean — the flyover", "items: object[] — the display list"],
        operations: ["project(x, y, z)", "add(layer, key, draw)", "polygon(points, style)", "plate(center, heading, length, width, style) — a flat plate with a text, e.g. a marker cover", "line(points, style)", "prism(footprint, z0, z1, colors)", "glow(at, radiusMM, colour, strength)", "label(at, text, style)", "dim(colour, amount)", "render()"],
      },
      { name: "SimpleView", file: "web/arail/core/simple.js", kind: "class", extends: "View", role: "Map and 2.5D: flat footprints, plain blocks, always day.", operations: ["block(footprint, z0, z1, colour)"] },
      { name: "colors", file: "web/arail/core/colors.js", kind: "module", role: "The corporate-design colours.", attributes: ["CD — the colours of the corporate design", "OVERLAY — colours over the camera image", "FONT"], operations: ["mix(a, b, t, alpha)", "shade(c, factor, alpha)", "moodColor(m, alpha, k)"] },
    ],
    relations: [
      { from: "World", to: "View", kind: "uses", label: "draw(view)" },
      { from: "View", to: "colors", kind: "depends" },
    ],
    activities: [{
      id: "draw", name: "World.draw and View.render",
      nodes: [
        ["s", "start"],
        ["a1", "action", "Night from the clock (unless set)", "World.draw"],
        ["d1", "decision", "The simple view?"],
        ["a2", "action", "Objects as flat footprints", "World.draw"],
        ["a3", "action", "Objects drawn", "LayoutObject.draw"],
        ["m1", "merge"],
        ["a4", "action", "Vehicles at the docks, line buses, the control system's trains", "ServiceManager.draw"],
        ["a5", "action", "The simulations (people, cars, machines), disruptions, the selection", "Simulation.draw"],
        ["a6", "action", "Sort: ground, solids far to near, overlays", "View.render"],
        ["d2", "decision", "Dark?"],
        ["a7", "action", "A Dunkelblau veil over the background", "View.render"],
        ["m2", "merge"],
        ["a8", "action", "Draw the items", "View.render"],
        ["e", "end"],
      ],
      edges: [["s", "a1"], ["a1", "d1"], ["d1", "a2", "yes"], ["d1", "a3", "no"], ["a2", "m1"], ["a3", "m1"], ["m1", "a4"], ["a4", "a5"], ["a5", "a6"], ["a6", "d2"], ["d2", "a7", "yes"], ["d2", "m2", "no"], ["a7", "m2"], ["m2", "a8"], ["a8", "e"]],
    }],
    rules: ["Layers: ground 0, solids 1, overlays 2; solids sorted far first.", "Night: colour × (1 − 0.62 n) + Dunkelblau × 0.3 n; emissive colours and overlays are not darkened.", "Nothing is queued that lies entirely outside the image; plain drawings share one save/restore."],
  },
  {
    id: "pick", group: "world", title: "Pointing at things",
    summary: "What is under a pixel of the stage, and an info card about it: people, vehicles, containers, buildings, stops, assets, in the camera view and the flyover.",
    description: "Everything the world draws can be pointed at. Layout objects are found on the ground (their footprint, with a tolerance) and, when tall, on their walls and roof (pickHeight). What moves is offered by whoever draws it: the managers of the world (the timetable's vehicles, the line buses, the control system's trains) and the simulations list their pickables, each with its outline on the layout and its height. Picking works in image pixels: the outline's box is projected, so a bus or a building is found where it is seen. The nearest thing that moves wins over the objects. Who offers a pickable gives its card (card(hit)): a title, what it is, a status line, rows, lists, related objects and actions; simulations add to the cards of objects (the people waiting at a stop, the condition of an asset, the trip of a train). The app shows the card's top as a tooltip and the whole card on a tap (app/inspect.js).",
    files: ["web/arail/core/pick.js"],
    classes: [
      {
        name: "pick", file: "web/arail/core/pick.js", kind: "module", role: "Pointing at things; cards are data.",
        attributes: ["PICK_TOLERANCE — CSS px around outlines: mouse 4, touch 12"],
        operations: ["pickAt(world, view, pixel, options) — the nearest thing that moves, else an object", "pickObject(world, view, pixel, ground, tol) — small objects before large ones, tables at their edges", "movingPickables(world, view) — of the managers and simulations", "objectPickable(o)", "projectedHull(view, p) — the image outline of its box", "groundPoint(view, pixel)", "findPickable(world, view, key)", "cardOf(hit) — the owner's card with every field"],
      },
    ],
    relations: [
      { from: "World", to: "pick", kind: "depends", label: "pick, card" },
      { from: "pick", to: "LayoutObject", kind: "uses", label: "footprint, card" },
      { from: "pick", to: "Simulation", kind: "uses", label: "pickables, card" },
      { from: "pick", to: "ServiceManager", kind: "uses", label: "pickables" },
      { from: "pick", to: "Transit", kind: "uses", label: "pickables" },
      { from: "pick", to: "TrainRegistry", kind: "uses", label: "pickables" },
    ],
    activities: [{
      id: "pick", name: "World.pick: what is at a pixel",
      description: "The app asks with the view of the last frame drawn (Inspector.pickAt): on every mouse move for the tooltip, on a tap for the card.",
      nodes: [
        ["s", "start"],
        ["a1", "action", "The pickables of the managers and the simulations", "movingPickables"],
        ["a2", "action", "Each one's box projected; the pixel inside or within the tolerance?", "projectedHull"],
        ["d1", "decision", "One or more there?"],
        ["a3", "action", "The one with the pixel inside, the nearest to the camera", "pickAt"],
        ["a4", "action", "The layout point at the pixel", "groundPoint"],
        ["a5", "action", "Objects there on the ground, tall ones also on their walls and roof", "pickObject"],
        ["d2", "decision", "Any?"],
        ["a6", "action", "Small objects before long and large ones; the smallest", "pickObject"],
        ["a7", "action", "Its card: the owner's, and what the simulations add to an object's", "World.card"],
        ["e1", "end"],
        ["e2", "end"],
      ],
      edges: [["s", "a1"], ["a1", "a2"], ["a2", "d1"], ["d1", "a3", "yes"], ["d1", "a4", "no"], ["a3", "a7"], ["a4", "a5"], ["a5", "d2"], ["d2", "a6", "yes"], ["d2", "e2", "no"], ["a6", "a7"], ["a7", "e1"]],
    }],
    rules: [
      "Over the camera image the real tables are not picked (they are the table itself); table modules only at their edges, as in the editor.",
      "People at a stop are the passenger simulation's; a resident or a traveller among them is described by its own simulation (describeAgent).",
      "A pickable's key stays the same while it exists, so an open card follows it (findPickable).",
      "Cards are English data; the app shows them.",
    ],
  },
];
