"""Generate the test fixtures for the JavaScript tests (tests/js).

    python -m arail_tools.fixtures tests/fixtures

Written files (raw RGBA images plus ``meta.json``):
- ``flight_NN.rgba``: frames of the synthetic camera path (960 x 540, like a phone video),
  with the true layout->image homography for each frame,
- ``dict_<name>.rgba``: markers 0-7 of every supported dictionary, generated by OpenCV,
  with the corner positions OpenCV reports (checks IDs *and* corner order of js-aruco2),
- ``example.rgba``: the synthetic example image of the web app,
- ``lab.rgba``: the real photo of the lab layout, downscaled (if the photo is present),
- ``synthetic-survey.webm``: a short video along the synthetic camera path (in-app survey test).
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np

from . import synthetic as syn
from .synthetic import cv2

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

# OpenCV name -> js-aruco2 name
DICTIONARIES = {
    "DICT_4X4_50": "ARUCO_4X4_1000",
    "DICT_5X5_50": "ARUCO_5X5_1000",
    "DICT_6X6_50": "ARUCO_6X6_1000",
    "DICT_7X7_50": "ARUCO_7X7_1000",
    "DICT_ARUCO_ORIGINAL": "ARUCO",
    "DICT_ARUCO_MIP_36h12": "ARUCO_MIP_36h12",
    "DICT_APRILTAG_36h11": "APRILTAG_36h11",
}
FLIGHT_SIZE = (960, 540)
LAB_PHOTO = os.path.join(ROOT, "examples", "media", "ebl-lab-photo.jpg")
LAB_WIDTH = 2400


def write_rgba(img: np.ndarray, path: str) -> None:
    code = cv2.COLOR_BGR2RGBA if img.ndim == 3 else cv2.COLOR_GRAY2RGBA
    cv2.cvtColor(img, code).tofile(path)


def detect(img: np.ndarray, dictionary: str) -> dict[int, list]:
    d = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, dictionary))
    p = cv2.aruco.DetectorParameters()
    p.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
    grey = img if img.ndim == 2 else cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    corners, ids, _ = cv2.aruco.ArucoDetector(d, p).detectMarkers(grey)
    if ids is None:
        return {}
    return {int(i): c.reshape(4, 2).tolist() for c, i in zip(corners, ids.flatten(), strict=True)}


def marker_bits(dictionary: str, mid: int) -> list[list[int]]:
    """Code bits of a marker (1 = white), sampled from the image OpenCV generates."""
    d = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, dictionary))
    n = d.markerSize
    cell = 20
    img = cv2.aruco.generateImageMarker(d, mid, (n + 2) * cell)
    return [
        [int(img[(y + 1) * cell + cell // 2, (x + 1) * cell + cell // 2] > 127) for x in range(n)] for y in range(n)
    ]


def main(argv=None) -> None:
    argv = sys.argv[1:] if argv is None else argv
    out = argv[0] if argv else os.path.join(ROOT, "tests", "fixtures")
    os.makedirs(out, exist_ok=True)
    meta: dict = {
        "marker_size_mm": syn.MARKER_SIZE_MM,
        "true_poses": syn.marker_poses_layout(),
        "f_true": syn.F_TRUE,
        "image_size": list(syn.IMAGE_SIZE),
        "flight_size": list(FLIGHT_SIZE),
        "platform_length_mm": syn.PLATFORM_LENGTH_MM,
        "platform_widths_mm": [p["width"] for p in syn.PLATFORMS],
    }

    # 1) camera path, every 4th frame, downscaled like a phone video
    tex, flight = syn.texture(), []
    for i, k in enumerate(range(0, 160, 4)):
        hidden = syn.hidden_markers(k)
        img, Hw = syn.render(tex, k, hidden)
        write_rgba(
            cv2.resize(img, FLIGHT_SIZE, interpolation=cv2.INTER_AREA), os.path.join(out, f"flight_{i:02d}.rgba")
        )
        flight.append({"k": k, "hidden": hidden, "H": syn.layout_homography(Hw).flatten().tolist()})
    meta["flight"] = flight

    # 2) every dictionary: markers 0-7, with OpenCV's corners and bits
    dicts = {}
    for cv_name, js_name in DICTIONARIES.items():
        d = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, cv_name))
        strip = np.full((300, 1000), 255, np.uint8)
        for i in range(8):
            strip[100:190, 20 + i * 120 : 110 + i * 120] = cv2.aruco.generateImageMarker(d, i, 90)
        strip = cv2.GaussianBlur(strip, (3, 3), 0.7)
        write_rgba(strip, os.path.join(out, f"dict_{cv_name}.rgba"))
        dicts[cv_name] = {
            "js": js_name,
            "size": [1000, 300],
            "corners": detect(strip, cv_name),
            "bits": {i: marker_bits(cv_name, i) for i in range(8)},
        }
    meta["dictionaries"] = dicts

    # 3) example image of the web app
    example = cv2.imread(os.path.join(ROOT, "web", "media", "synthetic-layout.jpg"))
    if example is not None:
        write_rgba(example, os.path.join(out, "example.rgba"))
        meta["example_size"] = [example.shape[1], example.shape[0]]

    # 4) real photo of the lab layout
    photo = cv2.imread(LAB_PHOTO)
    if photo is not None:
        s = LAB_WIDTH / photo.shape[1]
        lab = cv2.resize(photo, None, fx=s, fy=s, interpolation=cv2.INTER_AREA)
        write_rgba(lab, os.path.join(out, "lab.rgba"))
        meta["lab_size"] = [lab.shape[1], lab.shape[0]]
        meta["lab_opencv"] = detect(lab, "DICT_ARUCO_ORIGINAL")

    # 5) a short survey video of the synthetic layout (WebM/VP8: test browsers cannot decode H.264)
    path = os.path.join(out, "synthetic-survey.webm")
    writer = cv2.VideoWriter(path, cv2.VideoWriter_fourcc(*"VP80"), 10, FLIGHT_SIZE)
    if writer.isOpened():
        for k in range(0, 160, 2):
            img, _ = syn.render(tex, k, syn.hidden_markers(k))
            writer.write(cv2.resize(img, FLIGHT_SIZE, interpolation=cv2.INTER_AREA))
        writer.release()
        meta["survey_video"] = {"file": "synthetic-survey.webm", "frames": 80, "fps": 10}

    with open(os.path.join(out, "meta.json"), "w") as f:
        json.dump(meta, f, indent=1)
    print("fixtures written to", os.path.relpath(out))


if __name__ == "__main__":
    main()
